CREATE TABLE analysis_study_closures (
 id TEXT PRIMARY KEY NOT NULL,project_id TEXT NOT NULL,study_id TEXT NOT NULL UNIQUE,population_id TEXT NOT NULL,draw_id TEXT NOT NULL,dataset_revision_id TEXT NOT NULL,
 stopping_rule TEXT NOT NULL CHECK(stopping_rule IN('server_deadline','explicit_owner_close')),close_at TEXT,close_cause TEXT NOT NULL,
 close_actor_user_id TEXT,close_actor_subject_id TEXT,close_actor_role TEXT NOT NULL CHECK(close_actor_role IN('owner','system')),close_reason TEXT,
 effective_closed_at TEXT NOT NULL,recorded_at TEXT NOT NULL,selected_item_count INTEGER NOT NULL CHECK(selected_item_count BETWEEN 1 AND 10000),
 viewed_item_count INTEGER NOT NULL CHECK(viewed_item_count BETWEEN 0 AND selected_item_count),completed_item_count INTEGER NOT NULL CHECK(completed_item_count BETWEEN 0 AND selected_item_count),
 view_set_digest TEXT NOT NULL,assessment_version TEXT NOT NULL CHECK(assessment_version='representative-assessment-time/v1'),method TEXT NOT NULL,
 frozen_frame_digest TEXT NOT NULL,recomputed_frame_digest TEXT,frozen_draw_digest TEXT NOT NULL,recomputed_draw_digest TEXT,
 method_eligible INTEGER NOT NULL CHECK(method_eligible IN(0,1)),frame_reproducible INTEGER NOT NULL CHECK(frame_reproducible IN(0,1)),draw_complete INTEGER NOT NULL CHECK(draw_complete IN(0,1)),coding_complete INTEGER NOT NULL CHECK(coding_complete IN(0,1)),
 closure_item_count INTEGER NOT NULL CHECK(closure_item_count BETWEEN 1 AND selected_item_count),drawn_from_population_id TEXT NOT NULL,representative_of_population_id TEXT,representative_reason TEXT,
 assessment_digest TEXT NOT NULL,content_digest TEXT NOT NULL,closure_digest TEXT NOT NULL,created_at TEXT NOT NULL,created_command_token TEXT NOT NULL,
 UNIQUE(project_id,id),FOREIGN KEY(project_id,study_id) REFERENCES analysis_studies(project_id,id) ON DELETE CASCADE,
 FOREIGN KEY(project_id,id) REFERENCES analysis_study_closure_finalizations(project_id,closure_id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,population_id) REFERENCES analysis_populations(project_id,id),FOREIGN KEY(project_id,draw_id) REFERENCES analysis_population_draws(project_id,id),
 FOREIGN KEY(project_id,dataset_revision_id) REFERENCES dataset_revisions(project_id,id),FOREIGN KEY(project_id,close_actor_subject_id) REFERENCES governed_reviewer_subjects(project_id,id),
 CHECK((stopping_rule='server_deadline' AND close_cause='server_deadline' AND close_at IS NOT NULL AND close_actor_user_id IS NULL AND close_actor_subject_id IS NULL AND close_actor_role='system' AND close_reason IS NULL AND effective_closed_at=close_at AND recorded_at>=close_at)
 OR (stopping_rule='explicit_owner_close' AND close_cause='explicit_owner_close' AND close_at IS NULL AND close_actor_user_id IS NOT NULL AND close_actor_subject_id IS NOT NULL AND close_actor_role='owner' AND close_reason IS NOT NULL AND effective_closed_at=recorded_at))
) STRICT;
CREATE INDEX analysis_study_closure_command ON analysis_study_closures(created_command_token,project_id,population_id);
CREATE TABLE analysis_study_closure_items (
 id TEXT PRIMARY KEY NOT NULL,project_id TEXT NOT NULL,study_id TEXT NOT NULL,closure_id TEXT NOT NULL,study_item_id TEXT NOT NULL,draw_item_id TEXT NOT NULL,case_id TEXT NOT NULL,position INTEGER NOT NULL CHECK(position BETWEEN 0 AND 9999),
 item_state TEXT NOT NULL CHECK(item_state IN('uncoded','in_progress','completed')),item_event_version INTEGER NOT NULL CHECK(item_event_version>=0),current_event_id TEXT,current_event_digest TEXT,
 active_failure_observation_event_ids TEXT NOT NULL CHECK(json_valid(active_failure_observation_event_ids) AND json_type(active_failure_observation_event_ids)='array'),
 active_failure_observation_event_digests TEXT NOT NULL CHECK(json_valid(active_failure_observation_event_digests) AND json_type(active_failure_observation_event_digests)='array'),
 active_failure_assignment_event_ids TEXT NOT NULL CHECK(json_valid(active_failure_assignment_event_ids) AND json_type(active_failure_assignment_event_ids)='array'),
 active_failure_assignment_event_digests TEXT NOT NULL CHECK(json_valid(active_failure_assignment_event_digests) AND json_type(active_failure_assignment_event_digests)='array'),
 active_no_failure_event_id TEXT,active_no_failure_event_digest TEXT,completion_event_id TEXT,completion_event_digest TEXT,
 view_event_ids TEXT NOT NULL CHECK(json_valid(view_event_ids) AND json_type(view_event_ids)='array'),view_event_digests TEXT NOT NULL CHECK(json_valid(view_event_digests) AND json_type(view_event_digests)='array'),content_digest TEXT NOT NULL,created_at TEXT NOT NULL,
 UNIQUE(project_id,id),UNIQUE(closure_id,study_item_id),UNIQUE(closure_id,position),
 FOREIGN KEY(project_id,closure_id) REFERENCES analysis_study_closures(project_id,id) ON DELETE CASCADE,
 FOREIGN KEY(project_id,study_item_id) REFERENCES analysis_study_items(project_id,id),FOREIGN KEY(project_id,draw_item_id) REFERENCES analysis_population_draw_items(project_id,id)
) STRICT;
CREATE TABLE analysis_study_closure_finalizations (
 closure_id TEXT PRIMARY KEY NOT NULL,project_id TEXT NOT NULL,command_token TEXT NOT NULL,
 UNIQUE(project_id,closure_id),FOREIGN KEY(project_id,closure_id) REFERENCES analysis_study_closures(project_id,id) ON DELETE CASCADE
) STRICT;
-- Stop further coding as soon as closure materialization starts, including
-- writes after its finalizer in the same command.
CREATE TRIGGER analysis_closure_freeze_item_events BEFORE INSERT ON analysis_study_item_events WHEN EXISTS(SELECT 1 FROM analysis_study_closures WHERE study_id=NEW.study_id) BEGIN SELECT RAISE(ABORT,'study closure freezes coding'); END;
CREATE TRIGGER analysis_closure_freeze_assignments BEFORE INSERT ON analysis_observation_assignment_events WHEN EXISTS(SELECT 1 FROM analysis_study_closures WHERE study_id=NEW.study_id) BEGIN SELECT RAISE(ABORT,'study closure freezes assignments'); END;
CREATE TRIGGER analysis_closure_freeze_views BEFORE INSERT ON analysis_study_item_views WHEN NEW.counts_toward_closure=1 AND EXISTS(SELECT 1 FROM analysis_study_closures WHERE study_id=NEW.study_id) BEGIN SELECT RAISE(ABORT,'study closure freezes counted views'); END;
CREATE TRIGGER analysis_study_closure_insert BEFORE INSERT ON analysis_study_closures BEGIN
 SELECT CASE WHEN NEW.recorded_at IS NOT sqlite_command_time() OR NEW.created_at IS NOT sqlite_command_time() OR NEW.created_command_token IS NOT sqlite_command_token() THEN RAISE(ABORT,'closure requires command time and ownership') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM analysis_studies s JOIN analysis_population_draws d ON d.id=s.draw_id JOIN analysis_study_events e ON e.study_id=s.id AND e.event_type='coding_opened'
 WHERE s.id=NEW.study_id AND s.project_id=NEW.project_id AND s.population_id=NEW.population_id AND s.draw_id=NEW.draw_id AND s.dataset_revision_id=NEW.dataset_revision_id
 AND NEW.drawn_from_population_id=s.population_id AND NEW.stopping_rule=e.stopping_rule AND NEW.close_cause=e.stopping_rule AND NEW.selected_item_count=d.fixed_budget
 AND NEW.close_at IS e.close_at AND (SELECT to_state FROM analysis_study_events WHERE study_id=s.id ORDER BY version DESC LIMIT 1)='coding_open') THEN RAISE(ABORT,'closure requires exact open study draw and stopping rule') END;
 SELECT CASE WHEN NEW.stopping_rule='explicit_owner_close' AND (analysis_trimmed_text_v1(NEW.close_reason,2000) IS NOT 1 OR NOT EXISTS(SELECT 1 FROM governed_reviewer_subjects s JOIN project_members m ON m.project_id=s.project_id AND m.user_id=s.account_user_id WHERE s.project_id=NEW.project_id AND s.id=NEW.close_actor_subject_id AND s.account_user_id=NEW.close_actor_user_id AND m.role='owner')) THEN RAISE(ABORT,'explicit closure requires exact owner and reason') END;
 SELECT CASE WHEN analysis_population_frame_valid_v1(NEW.population_id,NEW.recomputed_frame_digest) IS NOT 1 THEN RAISE(ABORT,'closure recomputed frame mismatch') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM analysis_population_draws d JOIN analysis_populations p ON p.id=d.population_id WHERE d.id=NEW.draw_id
 AND NEW.method=d.method AND NEW.frozen_frame_digest=p.frame_digest AND NEW.frozen_draw_digest=d.draw_digest
 AND NEW.recomputed_draw_digest=analysis_sha256_v1(json_object('algorithmVersion',d.algorithm_version,'basis','rubrist-analysis-draw/v1','contentDigest',d.content_digest,'datasetRevisionId',d.dataset_revision_id,'drawExecutor',d.draw_executor,
 'drawItemContentDigests',json((SELECT json_group_array(content_digest ORDER BY position) FROM analysis_population_draw_items WHERE draw_id=d.id)),
 'fixedBudget',d.fixed_budget,'frameDigest',p.frame_digest,'inclusionProbability',json_object('denominator',d.inclusion_denominator,'numerator',d.inclusion_numerator),'method',d.method,'populationId',d.population_id,'populationSize',d.population_size,'rngVersion',d.rng_version,'seed',d.seed,'stoppingRule',d.stopping_rule))) THEN RAISE(ABORT,'closure recomputed draw mismatch') END;
 SELECT CASE WHEN NEW.method_eligible IS NOT (NEW.method='simple_random') OR NEW.frame_reproducible IS NOT (NEW.recomputed_frame_digest IS NOT NULL AND NEW.recomputed_frame_digest=NEW.frozen_frame_digest)
 OR NEW.draw_complete IS NOT (NEW.recomputed_draw_digest IS NOT NULL AND NEW.recomputed_draw_digest=NEW.frozen_draw_digest AND NEW.closure_item_count=NEW.selected_item_count)
 OR NEW.coding_complete IS NOT (NEW.recomputed_draw_digest IS NOT NULL AND NEW.recomputed_draw_digest=NEW.frozen_draw_digest AND NEW.closure_item_count=NEW.selected_item_count AND NEW.completed_item_count=NEW.selected_item_count)
 OR NEW.representative_reason IS NOT CASE WHEN NOT NEW.method_eligible THEN 'method_not_eligible' WHEN NOT NEW.frame_reproducible THEN 'frame_not_reproducible' WHEN NOT NEW.draw_complete THEN 'draw_not_complete' WHEN NOT NEW.coding_complete THEN 'coding_not_complete' ELSE NULL END
 OR NEW.representative_of_population_id IS NOT CASE WHEN NEW.representative_reason IS NULL THEN NEW.population_id ELSE NULL END THEN RAISE(ABORT,'closure representative claim mismatch') END;
 SELECT CASE WHEN NEW.assessment_digest IS NOT analysis_sha256_v1(json_object('basis','representative-assessment-time/v1','assessmentVersion',NEW.assessment_version,'codingComplete',json(CASE NEW.coding_complete WHEN 1 THEN 'true' ELSE 'false' END),'completedItemCount',NEW.completed_item_count,'drawComplete',json(CASE NEW.draw_complete WHEN 1 THEN 'true' ELSE 'false' END),'drawnFromPopulationId',NEW.drawn_from_population_id,'frameReproducible',json(CASE NEW.frame_reproducible WHEN 1 THEN 'true' ELSE 'false' END),'frozenDrawDigest',NEW.frozen_draw_digest,'frozenFrameDigest',NEW.frozen_frame_digest,'methodEligible',json(CASE NEW.method_eligible WHEN 1 THEN 'true' ELSE 'false' END),'recomputedDrawDigest',NEW.recomputed_draw_digest,'recomputedFrameDigest',NEW.recomputed_frame_digest,'representativeOfPopulationId',NEW.representative_of_population_id,'representativeReason',NEW.representative_reason,'selectedItemCount',NEW.selected_item_count)) THEN RAISE(ABORT,'closure assessment_digest mismatch') END;
 SELECT CASE WHEN NEW.closure_digest IS NOT analysis_sha256_v1(json_object('basis','analysis-study-closure/v1','assessmentDigest',NEW.assessment_digest,'assessmentVersion',NEW.assessment_version,'closeActorRole',NEW.close_actor_role,'closeActorSubjectId',NEW.close_actor_subject_id,'closeActorUserId',NEW.close_actor_user_id,'closeCause',NEW.close_cause,'closeReason',NEW.close_reason,'closureItemCount',NEW.closure_item_count,'codingComplete',json(CASE NEW.coding_complete WHEN 1 THEN 'true' ELSE 'false' END),'completedItemCount',NEW.completed_item_count,'contentDigest',NEW.content_digest,'datasetRevisionId',NEW.dataset_revision_id,'drawComplete',json(CASE NEW.draw_complete WHEN 1 THEN 'true' ELSE 'false' END),'drawId',NEW.draw_id,'drawnFromPopulationId',NEW.drawn_from_population_id,'effectiveClosedAt',NEW.effective_closed_at,'frameReproducible',json(CASE NEW.frame_reproducible WHEN 1 THEN 'true' ELSE 'false' END),'frozenDrawDigest',NEW.frozen_draw_digest,'frozenFrameDigest',NEW.frozen_frame_digest,'method',NEW.method,'methodEligible',json(CASE NEW.method_eligible WHEN 1 THEN 'true' ELSE 'false' END),'populationId',NEW.population_id,'recomputedDrawDigest',NEW.recomputed_draw_digest,'recomputedFrameDigest',NEW.recomputed_frame_digest,'recordedAt',NEW.recorded_at,'representativeOfPopulationId',NEW.representative_of_population_id,'representativeReason',NEW.representative_reason,'selectedItemCount',NEW.selected_item_count,'studyId',NEW.study_id,'viewSetDigest',NEW.view_set_digest,'viewedItemCount',NEW.viewed_item_count,'stoppingRule',json_object('kind',NEW.stopping_rule,'closeAt',NEW.close_at))) THEN RAISE(ABORT,'closure closure_digest mismatch') END;
END;
CREATE TRIGGER analysis_closure_freeze_cases_update BEFORE UPDATE ON cases WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) AND EXISTS(SELECT 1 FROM analysis_study_closures closure JOIN analysis_populations p ON p.id=closure.population_id JOIN cases c ON c.project_id=p.project_id WHERE c.id=OLD.id AND c.created_at>=p.window_start AND c.created_at<p.window_end AND closure.created_command_token=sqlite_command_token()) BEGIN SELECT RAISE(ABORT,'closure frame source cannot change in its creating command'); END;
CREATE TRIGGER analysis_closure_freeze_cases_delete BEFORE DELETE ON cases WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) AND EXISTS(SELECT 1 FROM analysis_study_closures closure JOIN analysis_populations p ON p.id=closure.population_id JOIN cases c ON c.project_id=p.project_id WHERE c.id=OLD.id AND c.created_at>=p.window_start AND c.created_at<p.window_end AND closure.created_command_token=sqlite_command_token()) BEGIN SELECT RAISE(ABORT,'closure frame source cannot change in its creating command'); END;
CREATE TRIGGER analysis_closure_freeze_raw_traces_update BEFORE UPDATE ON raw_traces WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) AND EXISTS(SELECT 1 FROM analysis_study_closures closure JOIN analysis_populations p ON p.id=closure.population_id JOIN cases c ON c.project_id=p.project_id WHERE c.raw_trace_id=OLD.id AND c.created_at>=p.window_start AND c.created_at<p.window_end AND closure.created_command_token=sqlite_command_token()) BEGIN SELECT RAISE(ABORT,'closure frame source cannot change in its creating command'); END;
CREATE TRIGGER analysis_closure_freeze_raw_traces_delete BEFORE DELETE ON raw_traces WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) AND EXISTS(SELECT 1 FROM analysis_study_closures closure JOIN analysis_populations p ON p.id=closure.population_id JOIN cases c ON c.project_id=p.project_id WHERE c.raw_trace_id=OLD.id AND c.created_at>=p.window_start AND c.created_at<p.window_end AND closure.created_command_token=sqlite_command_token()) BEGIN SELECT RAISE(ABORT,'closure frame source cannot change in its creating command'); END;
CREATE TRIGGER analysis_closure_freeze_identity BEFORE INSERT ON case_input_identity_records WHEN EXISTS(SELECT 1 FROM analysis_study_closures closure JOIN analysis_populations p ON p.id=closure.population_id JOIN cases c ON c.project_id=p.project_id WHERE c.id=NEW.source_case_id AND c.created_at>=p.window_start AND c.created_at<p.window_end AND closure.created_command_token=sqlite_command_token()) BEGIN SELECT RAISE(ABORT,'closure frame identity cannot change in its creating command'); END;
CREATE TRIGGER analysis_study_closures_immutable BEFORE UPDATE ON analysis_study_closures BEGIN SELECT RAISE(ABORT,'immutable study closure'); END;
CREATE TRIGGER analysis_study_closures_erase BEFORE DELETE ON analysis_study_closures WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'closure deletion requires project erasure'); END;
CREATE TRIGGER analysis_study_closure_items_immutable BEFORE UPDATE ON analysis_study_closure_items BEGIN SELECT RAISE(ABORT,'immutable study closure'); END;
CREATE TRIGGER analysis_study_closure_items_erase BEFORE DELETE ON analysis_study_closure_items WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'closure deletion requires project erasure'); END;
CREATE TRIGGER analysis_study_closure_finalizations_immutable BEFORE UPDATE ON analysis_study_closure_finalizations BEGIN SELECT RAISE(ABORT,'immutable study closure'); END;
CREATE TRIGGER analysis_study_closure_finalizations_erase BEFORE DELETE ON analysis_study_closure_finalizations WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'closure deletion requires project erasure'); END;
