-- Independently reconstruct closure-time item projections from append-only
-- events. Views do not invoke connection-scoped validators.
CREATE VIEW analysis_closure_item_expected AS
WITH scoped AS (
 SELECT c.id closure_id,c.effective_closed_at,i.* FROM analysis_study_closures c JOIN analysis_study_items i ON i.study_id=c.study_id
), projected AS (
 SELECT s.*,
 (SELECT e.id FROM analysis_study_item_events e WHERE e.study_item_id=s.id AND e.occurred_at<=s.effective_closed_at ORDER BY version DESC LIMIT 1) current_event_id,
 (SELECT e.id FROM analysis_study_item_events e WHERE e.study_item_id=s.id AND e.event_type='no_failure_observed' AND e.occurred_at<=s.effective_closed_at AND NOT EXISTS(SELECT 1 FROM analysis_study_item_events w WHERE w.target_event_id=e.id AND w.event_type='no_failure_withdrawn' AND w.occurred_at<=s.effective_closed_at) ORDER BY e.version DESC LIMIT 1) active_no_failure_event_id,
 (SELECT e.id FROM analysis_study_item_events e WHERE e.study_item_id=s.id AND e.event_type='coding_completed' AND e.occurred_at<=s.effective_closed_at AND NOT EXISTS(SELECT 1 FROM analysis_study_item_events w WHERE w.target_event_id=e.id AND w.event_type='coding_reopened' AND w.occurred_at<=s.effective_closed_at) ORDER BY e.version DESC LIMIT 1) completion_event_id,
 (SELECT json_group_array(v.id ORDER BY v.viewed_at,governed_utf16_sort_key_v1(v.id)) FROM analysis_study_item_views v WHERE v.study_item_id=s.id AND v.counts_toward_closure=1 AND v.viewed_at<=s.effective_closed_at) view_event_ids,
 (SELECT json_group_array(v.content_digest ORDER BY v.viewed_at,governed_utf16_sort_key_v1(v.id)) FROM analysis_study_item_views v WHERE v.study_item_id=s.id AND v.counts_toward_closure=1 AND v.viewed_at<=s.effective_closed_at) view_event_digests
 FROM scoped s
), failures AS (
 SELECT s.closure_id,s.id study_item_id,e.id observation_id,e.event_digest observation_digest,e.version,
 (SELECT a.id FROM analysis_observation_assignment_events a WHERE a.observation_event_id=e.id ORDER BY a.version DESC LIMIT 1) assignment_id,
 (SELECT a.event_digest FROM analysis_observation_assignment_events a WHERE a.observation_event_id=e.id ORDER BY a.version DESC LIMIT 1) assignment_digest
 FROM scoped s JOIN analysis_study_item_events e ON e.study_item_id=s.id
 WHERE e.event_type='failure_observed' AND e.occurred_at<=s.effective_closed_at AND NOT EXISTS(SELECT 1 FROM analysis_study_item_events w WHERE w.target_event_id=e.id AND w.event_type='failure_withdrawn' AND w.occurred_at<=s.effective_closed_at)
)
SELECT p.closure_id,p.project_id,p.study_id,p.id study_item_id,p.draw_item_id,p.case_id,p.position,
 CASE WHEN p.completion_event_id IS NOT NULL THEN 'completed' WHEN p.current_event_id IS NULL AND json_array_length(p.view_event_ids)=0 THEN 'uncoded' ELSE 'in_progress' END item_state,
 coalesce(head.version,0) item_event_version,p.current_event_id,head.event_digest current_event_digest,p.active_no_failure_event_id,n.event_digest active_no_failure_event_digest,p.completion_event_id,done.event_digest completion_event_digest,p.view_event_ids,p.view_event_digests,
 (SELECT json_group_array(observation_id ORDER BY version) FROM failures f WHERE f.closure_id=p.closure_id AND f.study_item_id=p.id) active_failure_observation_event_ids,
 (SELECT json_group_array(observation_digest ORDER BY version) FROM failures f WHERE f.closure_id=p.closure_id AND f.study_item_id=p.id) active_failure_observation_event_digests,
 (SELECT json_group_array(assignment_id ORDER BY version) FROM failures f WHERE f.closure_id=p.closure_id AND f.study_item_id=p.id) active_failure_assignment_event_ids,
 (SELECT json_group_array(assignment_digest ORDER BY version) FROM failures f WHERE f.closure_id=p.closure_id AND f.study_item_id=p.id) active_failure_assignment_event_digests
 FROM projected p LEFT JOIN analysis_study_item_events head ON head.id=p.current_event_id LEFT JOIN analysis_study_item_events n ON n.id=p.active_no_failure_event_id LEFT JOIN analysis_study_item_events done ON done.id=p.completion_event_id;
CREATE TRIGGER analysis_study_closure_item_insert BEFORE INSERT ON analysis_study_closure_items BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM analysis_study_closures c JOIN analysis_study_items i ON i.study_id=c.study_id AND i.project_id=c.project_id
 WHERE c.id=NEW.closure_id AND c.project_id=NEW.project_id AND c.study_id=NEW.study_id AND c.created_command_token=sqlite_command_token() AND NEW.created_at=c.created_at
 AND i.id=NEW.study_item_id AND i.draw_item_id=NEW.draw_item_id AND i.case_id=NEW.case_id AND i.position=NEW.position)
 OR EXISTS(SELECT 1 FROM analysis_study_closure_finalizations WHERE closure_id=NEW.closure_id) THEN RAISE(ABORT,'closure item requires exact creating bundle') END;
 SELECT CASE WHEN NEW.content_digest IS NOT analysis_sha256_v1(json_object('basis','analysis-study-closure-item/v1','activeFailureAssignmentEventDigests',json(NEW.active_failure_assignment_event_digests),'activeFailureAssignmentEventIds',json(NEW.active_failure_assignment_event_ids),'activeFailureObservationEventDigests',json(NEW.active_failure_observation_event_digests),'activeFailureObservationEventIds',json(NEW.active_failure_observation_event_ids),'activeNoFailureEventDigest',NEW.active_no_failure_event_digest,'activeNoFailureEventId',NEW.active_no_failure_event_id,'caseId',NEW.case_id,'completionEventDigest',NEW.completion_event_digest,'completionEventId',NEW.completion_event_id,'currentEventDigest',NEW.current_event_digest,'currentEventId',NEW.current_event_id,'drawItemId',NEW.draw_item_id,'itemEventVersion',CAST(NEW.item_event_version AS TEXT),'itemState',NEW.item_state,'position',NEW.position,'studyId',NEW.study_id,'studyItemId',NEW.study_item_id,'viewEventDigests',json(NEW.view_event_digests),'viewEventIds',json(NEW.view_event_ids))) THEN RAISE(ABORT,'closure item digest mismatch') END;
END;
CREATE TRIGGER analysis_study_closure_finalize BEFORE INSERT ON analysis_study_closure_finalizations BEGIN
 SELECT CASE WHEN NEW.command_token IS NOT sqlite_command_token() OR NOT EXISTS(SELECT 1 FROM analysis_study_closures WHERE id=NEW.closure_id AND project_id=NEW.project_id AND created_command_token=NEW.command_token) THEN RAISE(ABORT,'closure finalizer requires owning command') END;
 SELECT CASE WHEN EXISTS(SELECT study_item_id,draw_item_id,case_id,position,item_state,item_event_version,current_event_id,current_event_digest,active_no_failure_event_id,active_no_failure_event_digest,completion_event_id,completion_event_digest,governed_canonical_json_v1(view_event_ids),governed_canonical_json_v1(view_event_digests),governed_canonical_json_v1(active_failure_observation_event_ids),governed_canonical_json_v1(active_failure_observation_event_digests),governed_canonical_json_v1(active_failure_assignment_event_ids),governed_canonical_json_v1(active_failure_assignment_event_digests) FROM analysis_study_closure_items WHERE closure_id=NEW.closure_id EXCEPT SELECT study_item_id,draw_item_id,case_id,position,item_state,item_event_version,current_event_id,current_event_digest,active_no_failure_event_id,active_no_failure_event_digest,completion_event_id,completion_event_digest,governed_canonical_json_v1(view_event_ids),governed_canonical_json_v1(view_event_digests),governed_canonical_json_v1(active_failure_observation_event_ids),governed_canonical_json_v1(active_failure_observation_event_digests),governed_canonical_json_v1(active_failure_assignment_event_ids),governed_canonical_json_v1(active_failure_assignment_event_digests) FROM analysis_closure_item_expected WHERE closure_id=NEW.closure_id) OR EXISTS(SELECT study_item_id,draw_item_id,case_id,position,item_state,item_event_version,current_event_id,current_event_digest,active_no_failure_event_id,active_no_failure_event_digest,completion_event_id,completion_event_digest,governed_canonical_json_v1(view_event_ids),governed_canonical_json_v1(view_event_digests),governed_canonical_json_v1(active_failure_observation_event_ids),governed_canonical_json_v1(active_failure_observation_event_digests),governed_canonical_json_v1(active_failure_assignment_event_ids),governed_canonical_json_v1(active_failure_assignment_event_digests) FROM analysis_closure_item_expected WHERE closure_id=NEW.closure_id EXCEPT SELECT study_item_id,draw_item_id,case_id,position,item_state,item_event_version,current_event_id,current_event_digest,active_no_failure_event_id,active_no_failure_event_digest,completion_event_id,completion_event_digest,governed_canonical_json_v1(view_event_ids),governed_canonical_json_v1(view_event_digests),governed_canonical_json_v1(active_failure_observation_event_ids),governed_canonical_json_v1(active_failure_observation_event_digests),governed_canonical_json_v1(active_failure_assignment_event_ids),governed_canonical_json_v1(active_failure_assignment_event_digests) FROM analysis_study_closure_items WHERE closure_id=NEW.closure_id) THEN RAISE(ABORT,'closure item projections differ from exact history') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM analysis_study_closures c WHERE c.id=NEW.closure_id
 AND c.closure_item_count=c.selected_item_count AND c.closure_item_count=(SELECT count(*) FROM analysis_study_closure_items WHERE closure_id=c.id)
 AND c.completed_item_count=(SELECT count(*) FROM analysis_study_closure_items WHERE closure_id=c.id AND item_state='completed')
 AND c.viewed_item_count=(SELECT count(*) FROM analysis_study_closure_items WHERE closure_id=c.id AND json_array_length(view_event_ids)>0)
 AND c.content_digest=analysis_sha256_v1(json_object('basis','analysis-study-closure-content/v1','closureItemContentDigests',json((SELECT json_group_array(content_digest ORDER BY position) FROM analysis_study_closure_items WHERE closure_id=c.id))))
 AND c.view_set_digest=analysis_sha256_v1(json_object('basis','analysis-study-view-set/v1','viewEventDigests',json((SELECT json_group_array(v.value ORDER BY i.position,CAST(v.key AS INTEGER)) FROM analysis_study_closure_items i,json_each(i.view_event_digests) v WHERE i.closure_id=c.id))))
 AND EXISTS(SELECT 1 FROM analysis_study_events e WHERE e.study_id=c.study_id AND e.project_id=c.project_id AND e.event_type='coding_closed' AND e.closure_id=c.id AND e.closure_digest=c.closure_digest AND e.close_cause=c.close_cause
 AND e.actor_role=c.close_actor_role AND e.actor_user_id IS c.close_actor_user_id AND e.actor_subject_id IS c.close_actor_subject_id AND e.reason IS c.close_reason AND e.occurred_at=c.recorded_at)) THEN RAISE(ABORT,'closure requires complete digest-bound items and close event') END;
END;
DROP TRIGGER analysis_study_closure_transition_staged;
CREATE TRIGGER analysis_study_closure_event_insert BEFORE INSERT ON analysis_study_events WHEN NEW.event_type IN('coding_closed','study_completed') BEGIN
 SELECT CASE WHEN NEW.event_type='coding_closed' AND (NEW.from_state<>'coding_open' OR NEW.to_state<>'coding_closed' OR NOT EXISTS(SELECT 1 FROM analysis_study_closures c WHERE c.id=NEW.closure_id AND c.project_id=NEW.project_id AND c.study_id=NEW.study_id
 AND c.closure_digest=NEW.closure_digest AND c.close_cause=NEW.close_cause AND c.close_actor_role=NEW.actor_role AND c.close_actor_user_id IS NEW.actor_user_id AND c.close_actor_subject_id IS NEW.actor_subject_id AND c.close_reason IS NEW.reason
 AND c.recorded_at=NEW.occurred_at AND c.created_command_token=sqlite_command_token())) THEN RAISE(ABORT,'study close event requires exact closure') END;
 SELECT CASE WHEN NEW.event_type='study_completed' AND (NEW.from_state<>'coding_closed' OR NEW.to_state<>'completed' OR NEW.actor_role<>'owner'
 OR NEW.expected_closure_digest IS NOT (SELECT closure_digest FROM analysis_study_events WHERE study_id=NEW.study_id ORDER BY version DESC LIMIT 1)
 OR NOT EXISTS(SELECT 1 FROM analysis_study_closures c JOIN analysis_study_closure_finalizations f ON f.closure_id=c.id WHERE c.study_id=NEW.study_id)) THEN RAISE(ABORT,'study completion requires exact finalized closure') END;
END;
