-- Close labeling atomically, expiring only pending tasks at the fixed stop.
DROP TRIGGER governed_task_event_stage;
DROP TRIGGER governed_task_event_insert;
CREATE TRIGGER governed_task_event_insert BEFORE INSERT ON governed_review_task_events BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_tasks t JOIN governed_review_batch_states b ON b.batch_id=t.batch_id WHERE t.id=NEW.task_id AND t.project_id=NEW.project_id AND b.state='open' AND t.created_at<=NEW.occurred_at AND ((NEW.event_kind='expired' AND NEW.actor_subject_id IS NULL AND NEW.actor_role_at_review IS NULL) OR (NEW.event_kind<>'expired' AND t.reviewer_subject_id IS NEW.actor_subject_id AND t.reviewer_role_at_review IS NEW.actor_role_at_review))) THEN RAISE(ABORT,'task action requires open batch and exact reviewer snapshot') END;
 SELECT CASE WHEN NEW.expected_previous_state_version<>(SELECT state_version FROM governed_review_task_states WHERE task_id=NEW.task_id) OR NEW.state_version<>NEW.expected_previous_state_version+1 OR NEW.sequence<>NEW.state_version OR NEW.previous_event_digest IS NOT (SELECT event_digest FROM governed_review_task_events WHERE task_id=NEW.task_id ORDER BY state_version DESC LIMIT 1) THEN RAISE(ABORT,'governed task state version conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_task_states WHERE task_id=NEW.task_id AND ((state='assigned' AND NEW.event_kind='viewed') OR (state='viewed' AND NEW.event_kind='deferred') OR (state='deferred' AND NEW.event_kind='resumed') OR (state IN('viewed','withdrawn') AND NEW.event_kind='label_submitted') OR (state='submitted' AND NEW.event_kind='label_withdrawn') OR (state IN('assigned','viewed','withdrawn') AND NEW.event_kind='expired'))) THEN RAISE(ABORT,'invalid governed task transition') END;
 SELECT CASE WHEN NEW.event_kind='expired' AND governed_timestamp_v1(NEW.occurred_at)<(SELECT governed_timestamp_v1(b.stop_at) FROM governed_review_batches b JOIN governed_review_tasks t ON t.batch_id=b.id WHERE t.id=NEW.task_id) THEN RAISE(ABORT,'expiry requires fixed stop') END;
 SELECT CASE WHEN NEW.event_kind='viewed' AND (NEW.view_digest IS NOT governed_bytes_v1_digest(NEW.canonical_view_bytes) OR analysis_governed_task_view_valid_v1(NEW.task_id,NEW.project_id,NEW.canonical_view_bytes)<>1) THEN RAISE(ABORT,'blind view bytes must match exact immutable task projection') END;
 SELECT CASE WHEN NEW.event_kind='label_submitted' AND NOT EXISTS(SELECT 1 FROM governed_review_labels l WHERE l.id=NEW.label_id AND l.project_id=NEW.project_id AND l.task_id=NEW.task_id AND l.reviewer_subject_id=NEW.actor_subject_id AND l.created_command_token=sqlite_command_token() AND l.created_at=NEW.occurred_at AND ((SELECT state FROM governed_review_task_states WHERE task_id=NEW.task_id)<>'withdrawn' OR l.replaces_label_id IS (SELECT label_id FROM governed_review_task_events WHERE task_id=NEW.task_id ORDER BY state_version DESC LIMIT 1))) THEN RAISE(ABORT,'submission requires current command label for exact reviewer') END;
 SELECT CASE WHEN NEW.event_kind='label_withdrawn' AND NEW.label_id IS NOT (SELECT label_id FROM governed_active_review_labels WHERE task_id=NEW.task_id) THEN RAISE(ABORT,'withdrawal must name active label') END;
 SELECT CASE WHEN NEW.event_digest IS NOT governed_content_v1_digest('governed-review-task-event/v1',json_object('activity',NEW.activity,'actorRoleAtReview',NEW.actor_role_at_review,'actorSubjectId',NEW.actor_subject_id,'canonicalizationVersion',NEW.canonicalization_version,'eventKind',NEW.event_kind,'exposureClass',NEW.exposure_class,'labelId',NEW.label_id,'reason',NEW.reason,'canonicalViewBytesBase64',CASE WHEN NEW.canonical_view_bytes IS NULL THEN NULL ELSE governed_base64_v1(NEW.canonical_view_bytes) END,'previousEventDigest',NEW.previous_event_digest,'sequence',NEW.sequence,'stateVersion',NEW.state_version,'taskId',NEW.task_id,'viewContractVersion',NEW.view_contract_version,'viewDigest',NEW.view_digest)) THEN RAISE(ABORT,'governed stream event digest mismatch') END;
END;
CREATE VIEW governed_review_item_resolutions AS
 SELECT i.id batch_item_id,i.batch_id,i.project_id,
 CASE WHEN count(t.id)<>b.required_labels_per_item OR count(a.label_id)<>b.required_labels_per_item THEN 'coverage_gap'
 WHEN sum(a.label='pass')=b.required_labels_per_item OR sum(a.label='fail')=b.required_labels_per_item THEN CASE b.required_labels_per_item WHEN 1 THEN 'single_rater' ELSE 'unanimous' END
 ELSE 'conflict' END resolution_kind,
 CASE WHEN count(t.id)=b.required_labels_per_item AND count(a.label_id)=b.required_labels_per_item AND (sum(a.label='pass')=b.required_labels_per_item OR sum(a.label='fail')=b.required_labels_per_item) THEN min(a.label) ELSE NULL END resolved_label,
 NULL adjudication_id
 FROM governed_review_batch_items i JOIN governed_review_batches b ON b.id=i.batch_id LEFT JOIN governed_review_tasks t ON t.batch_item_id=i.id LEFT JOIN governed_active_review_labels a ON a.task_id=t.id GROUP BY i.id;
DROP TRIGGER governed_batch_event_stage;
CREATE TRIGGER governed_batch_event_stage BEFORE INSERT ON governed_review_batch_events WHEN NEW.event_kind NOT IN('open','abandoned','labeling_closed','resolved','incomplete') BEGIN SELECT RAISE(ABORT,'governed alignment adjudication and truth transitions require complete port'); END;
DROP TRIGGER governed_batch_event_insert;
CREATE TRIGGER governed_batch_event_insert BEFORE INSERT ON governed_review_batch_events BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_batches b WHERE b.id=NEW.batch_id AND b.project_id=NEW.project_id AND b.created_at<=NEW.occurred_at AND EXISTS(SELECT 1 FROM governed_review_batch_finalizations WHERE batch_id=b.id)) THEN RAISE(ABORT,'batch event requires current owning command and finalized draft') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_reviewer_subjects s JOIN project_members pm ON pm.project_id=s.project_id AND pm.user_id=s.account_user_id WHERE s.project_id=NEW.project_id AND s.id=NEW.actor_subject_id AND pm.role='owner' AND NEW.actor_role_at_review='owner') THEN RAISE(ABORT,'batch transition requires live owner') END;
 SELECT CASE WHEN NEW.expected_previous_state_version<>(SELECT state_version FROM governed_review_batch_states WHERE batch_id=NEW.batch_id) OR NEW.state_version<>NEW.expected_previous_state_version+1 OR NEW.sequence<>NEW.state_version OR NEW.previous_event_digest IS NOT (SELECT event_digest FROM governed_review_batch_events WHERE batch_id=NEW.batch_id ORDER BY state_version DESC LIMIT 1) THEN RAISE(ABORT,'governed batch state version conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_batch_states WHERE batch_id=NEW.batch_id AND ((state='draft' AND NEW.event_kind IN('open','abandoned')) OR (state='open' AND NEW.event_kind IN('abandoned','labeling_closed')) OR (state='labeling_closed' AND NEW.event_kind IN('resolved','incomplete')))) THEN RAISE(ABORT,'invalid governed batch transition') END;
 SELECT CASE WHEN NEW.dataset_revision_id IS NOT NULL OR NEW.representative_of_population_id IS NOT NULL OR json_array_length(NEW.representative_ineligible_reasons)<>0 OR governed_jsonb_octets_v1(NEW.details)>65536 THEN RAISE(ABORT,'invalid pre-barrier batch details') END;
 INSERT INTO governed_review_task_events(id,project_id,task_id,sequence,state_version,expected_previous_state_version,event_kind,reason,previous_event_digest,event_digest,idempotency_key,request_digest,occurred_at)
 SELECT 'grte_expired_'||NEW.id||'_'||t.id,t.project_id,t.id,ts.state_version+1,ts.state_version+1,ts.state_version,'expired','fixed_stop',e.event_digest,
 governed_content_v1_digest('governed-review-task-event/v1',json_object('activity',NULL,'actorRoleAtReview',NULL,'actorSubjectId',NULL,'canonicalizationVersion',NULL,'eventKind','expired','exposureClass',NULL,'labelId',NULL,'canonicalViewBytesBase64',NULL,'previousEventDigest',e.event_digest,'reason','fixed_stop','sequence',ts.state_version+1,'stateVersion',ts.state_version+1,'taskId',t.id,'viewContractVersion',NULL,'viewDigest',NULL)),
 'expire:'||NEW.id,governed_content_v1_digest('governed-review-expiry-request/v1',json_object('batchEventId',NEW.id,'taskId',t.id)),NEW.occurred_at
 FROM governed_review_tasks t JOIN governed_review_task_states ts ON ts.task_id=t.id JOIN governed_review_batches b ON b.id=t.batch_id LEFT JOIN governed_review_task_events e ON e.task_id=t.id AND e.state_version=ts.state_version
 WHERE t.batch_id=NEW.batch_id AND NEW.event_kind='labeling_closed' AND governed_timestamp_v1(NEW.occurred_at)>=governed_timestamp_v1(b.stop_at) AND ts.state IN('assigned','viewed','withdrawn') ORDER BY t.id;
 SELECT CASE WHEN NEW.event_kind='labeling_closed' AND EXISTS(SELECT 1 FROM governed_review_task_states WHERE batch_id=NEW.batch_id AND state NOT IN('submitted','deferred','expired')) THEN RAISE(ABORT,'labeling closure requires terminal tasks or fixed stop') END;
 SELECT CASE WHEN NEW.event_kind='resolved' AND EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind NOT IN('single_rater','unanimous','adjudicated')) THEN RAISE(ABORT,'batch resolution requires complete resolved truth') END;
 SELECT CASE WHEN NEW.event_kind='incomplete' AND NOT EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind IN('coverage_gap','unresolvable')) THEN RAISE(ABORT,'incomplete requires coverage gap or unresolvable adjudication') END;
 SELECT CASE WHEN NEW.event_digest IS NOT governed_content_v1_digest('governed-review-batch-event/v1',json_object('actorRoleAtReview',NEW.actor_role_at_review,'actorSubjectId',NEW.actor_subject_id,'batchId',NEW.batch_id,'datasetRevisionId',NEW.dataset_revision_id,'details',json(NEW.details),'eventKind',NEW.event_kind,'previousEventDigest',NEW.previous_event_digest,'representativeIneligibleReasons',json(NEW.representative_ineligible_reasons),'representativeOfPopulationId',NEW.representative_of_population_id,'sequence',NEW.sequence,'stateVersion',NEW.state_version)) THEN RAISE(ABORT,'governed stream event digest mismatch') END;
END;
