-- Nonsealed freeze retains a complete revision, exact truth links and scope.
ALTER TABLE governed_review_batch_events ADD COLUMN created_command_token TEXT;
CREATE TRIGGER governed_batch_event_command BEFORE INSERT ON governed_review_batch_events WHEN NEW.created_command_token IS NOT sqlite_command_token() BEGIN SELECT RAISE(ABORT,'batch event requires owning command token'); END;
CREATE VIEW governed_review_representative_reasons AS
 SELECT b.id batch_id,'cannot_determine_present' reason FROM governed_review_batches b WHERE EXISTS(SELECT 1 FROM governed_active_review_labels WHERE batch_id=b.id AND label='cannot_determine')
 UNION ALL SELECT id,'collection_provenance_unverified' FROM governed_review_batches WHERE json_type(population_collection_provenance)='object' AND NOT EXISTS(SELECT 1 FROM json_each(population_collection_provenance))
 UNION ALL SELECT id,'draw_not_reproducible' FROM governed_review_batches WHERE selection_method IN('simple_random','stratified_random') AND (selection_seed IS NULL OR rng_version IS NULL)
 UNION ALL SELECT id,'draw_not_server_executed' FROM governed_review_batches WHERE draw_executed_by<>'rubrist_server'
 UNION ALL SELECT id,'population_frame_incomplete' FROM governed_review_batches WHERE json_type(population_definition)='object' AND NOT EXISTS(SELECT 1 FROM json_each(population_definition))
 UNION ALL SELECT b.id,'review_coverage_incomplete' FROM governed_review_batches b WHERE EXISTS(SELECT 1 FROM governed_review_task_states WHERE batch_id=b.id AND state<>'submitted')
 UNION ALL SELECT id,'selection_method_not_eligible' FROM governed_review_batches WHERE selection_method NOT IN('simple_random','stratified_random');
CREATE TRIGGER dataset_revision_native_truth_freeze BEFORE INSERT ON dataset_revision_finalizations WHEN EXISTS(SELECT 1 FROM dataset_revisions WHERE id=NEW.revision_id AND provenance_level='governed_blind') BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_batch_events WHERE dataset_revision_id=NEW.revision_id AND project_id=NEW.project_id AND event_kind='frozen' AND occurred_at=sqlite_command_time() AND created_command_token=sqlite_command_token()) THEN RAISE(ABORT,'native governed revision requires same-command frozen batch') END;
END;
DROP TRIGGER governed_batch_event_stage;
DROP TRIGGER governed_batch_event_insert;
CREATE TRIGGER governed_batch_event_insert BEFORE INSERT ON governed_review_batch_events BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_batches b WHERE b.id=NEW.batch_id AND b.project_id=NEW.project_id AND b.created_at<=NEW.occurred_at AND EXISTS(SELECT 1 FROM governed_review_batch_finalizations WHERE batch_id=b.id)) THEN RAISE(ABORT,'batch event requires current owning command and finalized draft') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_reviewer_subjects s JOIN project_members pm ON pm.project_id=s.project_id AND pm.user_id=s.account_user_id WHERE s.project_id=NEW.project_id AND s.id=NEW.actor_subject_id AND pm.role='owner' AND NEW.actor_role_at_review='owner') THEN RAISE(ABORT,'batch transition requires live owner') END;
 SELECT CASE WHEN NEW.expected_previous_state_version<>(SELECT state_version FROM governed_review_batch_states WHERE batch_id=NEW.batch_id) OR NEW.state_version<>NEW.expected_previous_state_version+1 OR NEW.sequence<>NEW.state_version OR NEW.previous_event_digest IS NOT (SELECT event_digest FROM governed_review_batch_events WHERE batch_id=NEW.batch_id ORDER BY state_version DESC LIMIT 1) THEN RAISE(ABORT,'governed batch state version conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_batch_states WHERE batch_id=NEW.batch_id AND ((state='draft' AND NEW.event_kind IN('open','abandoned')) OR (state='open' AND NEW.event_kind IN('abandoned','labeling_closed')) OR (state='labeling_closed' AND NEW.event_kind IN('alignment_open','adjudicating','resolved','incomplete')) OR (state='alignment_open' AND NEW.event_kind IN('adjudicating','incomplete')) OR (state='adjudicating' AND NEW.event_kind IN('resolved','incomplete')) OR (state='resolved' AND NEW.event_kind='frozen'))) THEN RAISE(ABORT,'invalid governed batch transition') END;
 SELECT CASE WHEN (NEW.event_kind<>'frozen' AND (NEW.dataset_revision_id IS NOT NULL OR NEW.representative_of_population_id IS NOT NULL OR json_array_length(NEW.representative_ineligible_reasons)<>0)) OR governed_jsonb_octets_v1(NEW.details)>65536 THEN RAISE(ABORT,'invalid pre-barrier batch details') END;
 INSERT INTO governed_review_task_events(id,project_id,task_id,sequence,state_version,expected_previous_state_version,event_kind,reason,previous_event_digest,event_digest,idempotency_key,request_digest,occurred_at)
 SELECT 'grte_expired_'||NEW.id||'_'||t.id,t.project_id,t.id,ts.state_version+1,ts.state_version+1,ts.state_version,'expired','fixed_stop',e.event_digest,
 governed_content_v1_digest('governed-review-task-event/v1',json_object('activity',NULL,'actorRoleAtReview',NULL,'actorSubjectId',NULL,'canonicalizationVersion',NULL,'eventKind','expired','exposureClass',NULL,'labelId',NULL,'canonicalViewBytesBase64',NULL,'previousEventDigest',e.event_digest,'reason','fixed_stop','sequence',ts.state_version+1,'stateVersion',ts.state_version+1,'taskId',t.id,'viewContractVersion',NULL,'viewDigest',NULL)),
 'expire:'||NEW.id,governed_content_v1_digest('governed-review-expiry-request/v1',json_object('batchEventId',NEW.id,'taskId',t.id)),NEW.occurred_at
 FROM governed_review_tasks t JOIN governed_review_task_states ts ON ts.task_id=t.id JOIN governed_review_batches b ON b.id=t.batch_id LEFT JOIN governed_review_task_events e ON e.task_id=t.id AND e.state_version=ts.state_version
 WHERE t.batch_id=NEW.batch_id AND NEW.event_kind='labeling_closed' AND governed_timestamp_v1(NEW.occurred_at)>=governed_timestamp_v1(b.stop_at) AND ts.state IN('assigned','viewed','withdrawn') ORDER BY t.id;
 SELECT CASE WHEN NEW.event_kind='labeling_closed' AND EXISTS(SELECT 1 FROM governed_review_task_states WHERE batch_id=NEW.batch_id AND state NOT IN('submitted','deferred','expired')) THEN RAISE(ABORT,'labeling closure requires terminal tasks or fixed stop') END;
 SELECT CASE WHEN NEW.event_kind='resolved' AND EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind NOT IN('single_rater','unanimous','adjudicated')) THEN RAISE(ABORT,'batch resolution requires complete resolved truth') END;
 SELECT CASE WHEN NEW.event_kind='incomplete' AND NOT EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind IN('coverage_gap','unresolvable')) THEN RAISE(ABORT,'incomplete requires coverage gap or unresolvable adjudication') END;
 SELECT CASE WHEN NEW.event_kind IN('alignment_open','adjudicating') AND (EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind='coverage_gap') OR NOT EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind='conflict')) THEN RAISE(ABORT,'alignment and adjudication require complete coverage and conflict') END;
 SELECT CASE WHEN NEW.event_kind='adjudicating' AND (SELECT state FROM governed_review_batch_states WHERE batch_id=NEW.batch_id)='alignment_open' AND NOT EXISTS(SELECT 1 FROM governed_review_alignment_events WHERE batch_id=NEW.batch_id AND event_kind='closed' AND sequence=(SELECT max(sequence) FROM governed_review_alignment_events WHERE batch_id=NEW.batch_id)) THEN RAISE(ABORT,'alignment must close before adjudication') END;
 SELECT CASE WHEN NEW.event_kind='frozen' AND NOT EXISTS(SELECT 1 FROM governed_review_batches b JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id AND r.project_id=b.project_id WHERE b.id=NEW.batch_id AND b.role_intent<>'sealed_validation' AND r.criterion_version_id=b.criterion_version_id AND r.role=b.role_intent AND r.item_count=b.fixed_budget AND r.provenance_level='governed_blind' AND r.created_at=sqlite_command_time() AND r.source_kind='collection_snapshot' AND NOT EXISTS(SELECT 1 FROM dataset_revision_finalizations WHERE revision_id=r.id) AND (SELECT count(*) FROM governed_dataset_truth_links WHERE dataset_revision_id=r.id)=b.fixed_budget AND NOT EXISTS(SELECT 1 FROM governed_review_batch_items i WHERE i.batch_id=b.id AND (SELECT count(*) FROM governed_dataset_truth_links t WHERE t.batch_item_id=i.id AND t.dataset_revision_id=r.id AND t.created_command_token=sqlite_command_token())<>1)) THEN RAISE(ABORT,'freeze requires complete exact same-command native truth revision') END;
 SELECT CASE WHEN NEW.event_kind='frozen' AND (governed_canonical_json_v1(NEW.representative_ineligible_reasons) IS NOT governed_canonical_json_v1((SELECT json_group_array(reason ORDER BY reason) FROM governed_review_representative_reasons WHERE batch_id=NEW.batch_id)) OR NEW.representative_of_population_id IS NOT (SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_representative_reasons WHERE batch_id=b.id) THEN b.population_id ELSE NULL END FROM governed_review_batches b WHERE b.id=NEW.batch_id)) THEN RAISE(ABORT,'freeze representative scope must match retained evidence') END;
 SELECT CASE WHEN NEW.event_digest IS NOT governed_content_v1_digest('governed-review-batch-event/v1',json_object('actorRoleAtReview',NEW.actor_role_at_review,'actorSubjectId',NEW.actor_subject_id,'batchId',NEW.batch_id,'datasetRevisionId',NEW.dataset_revision_id,'details',json(NEW.details),'eventKind',NEW.event_kind,'previousEventDigest',NEW.previous_event_digest,'representativeIneligibleReasons',json(NEW.representative_ineligible_reasons),'representativeOfPopulationId',NEW.representative_of_population_id,'sequence',NEW.sequence,'stateVersion',NEW.state_version)) THEN RAISE(ABORT,'governed stream event digest mismatch') END;
END;

DROP TRIGGER dataset_revision_item_owner;
CREATE TRIGGER dataset_revision_item_owner BEFORE INSERT ON dataset_revision_items
BEGIN
  SELECT CASE WHEN EXISTS(SELECT 1 FROM dataset_revision_finalizations WHERE revision_id=NEW.revision_id) THEN RAISE(ABORT,'immutable finalized revision') END;
  SELECT CASE WHEN sqlite_dataset_item_valid_v2(NEW.input_digest,NEW.item_digest,NEW.payload_snapshot,NEW.reference_label,NEW.reference_fail_step,NEW.reference_provenance,NEW.note)=0 THEN RAISE(ABORT,'dataset item digest mismatch') END;
  SELECT CASE WHEN NEW.source_case_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM cases WHERE project_id=NEW.project_id AND id=NEW.source_case_id AND sqlite_dataset_payload_equal(normalized_payload,NEW.payload_snapshot)=1) THEN RAISE(ABORT,'dataset item source snapshot mismatch') END;
  SELECT CASE WHEN NEW.source_case_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM case_input_identity_records WHERE project_id=NEW.project_id AND source_case_id=NEW.source_case_id AND input_digest=NEW.input_digest) THEN RAISE(ABORT,'dataset item input identity mismatch') END;
  SELECT CASE WHEN NEW.source_dataset_item_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM dataset_items d JOIN dataset_revisions r ON r.source_dataset_id=d.dataset_id AND r.project_id=d.project_id WHERE r.id=NEW.revision_id AND d.id=NEW.source_dataset_item_id AND d.project_id=NEW.project_id AND d.case_id=NEW.source_case_id) THEN RAISE(ABORT,'dataset item source membership mismatch') END;
  SELECT CASE WHEN EXISTS(SELECT 1 FROM dataset_revision_items i JOIN dataset_revisions r ON r.id=i.revision_id JOIN dataset_revisions target ON target.id=NEW.revision_id WHERE i.project_id=NEW.project_id AND i.input_digest=NEW.input_digest AND (r.role='sealed_validation')<>(target.role='sealed_validation')) THEN RAISE(ABORT,'sealed input overlap requires governed declassification') END;
END;

CREATE TRIGGER dataset_revision_blind_payload_finalize BEFORE INSERT ON dataset_revision_finalizations BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM dataset_revision_items i WHERE i.revision_id=NEW.revision_id AND json_type(i.payload_snapshot,'$.metadata') IS NULL AND NOT EXISTS(SELECT 1 FROM governed_dataset_truth_links t WHERE t.dataset_revision_item_id=i.id AND t.dataset_revision_id=i.revision_id AND t.project_id=i.project_id)) THEN RAISE(ABORT,'metadata-free revision payload requires authoritative native or imported truth') END;
END;
