-- Protected intake frames can now form immutable drafts; sealed execution
-- remains blocked until its live separation gates land.
DROP TRIGGER governed_batch_source_stage;
CREATE TRIGGER governed_batch_source_stage BEFORE INSERT ON governed_review_batches WHEN NEW.source_population_kind='analysis_promotion_handoff' BEGIN SELECT RAISE(ABORT,'governed source requires complete promotion port'); END;
CREATE TRIGGER governed_sealed_execution_stage BEFORE INSERT ON governed_review_batch_events WHEN EXISTS(SELECT 1 FROM governed_review_batches WHERE id=NEW.batch_id AND role_intent='sealed_validation') BEGIN SELECT RAISE(ABORT,'sealed execution requires complete live separation gates'); END;
CREATE TRIGGER governed_sealed_batch_source BEFORE INSERT ON governed_review_batches WHEN NEW.source_population_kind='sealed_intake' BEGIN
 SELECT CASE WHEN NEW.role_intent<>'sealed_validation' OR NOT EXISTS(SELECT 1 FROM governed_sealed_intake_populations p JOIN governed_sealed_intake_finalizations f ON f.intake_id=p.id WHERE p.id=NEW.source_population_id AND p.project_id=NEW.project_id AND p.id=NEW.population_id AND p.frame_count=NEW.population_size AND p.frame_digest=NEW.population_digest AND p.custodian_subject_id=NEW.custodian_subject_id AND p.custodian_role_at_review=NEW.custodian_role_at_review AND governed_canonical_json_v1(p.population_definition)=governed_canonical_json_v1(NEW.population_definition) AND governed_canonical_json_v1(p.collection_provenance)=governed_canonical_json_v1(NEW.population_collection_provenance) AND CASE WHEN p.window_start IS NULL THEN NULL ELSE governed_timestamp_v1(p.window_start) END IS CASE WHEN NEW.window_start IS NULL THEN NULL ELSE governed_timestamp_v1(NEW.window_start) END AND CASE WHEN p.window_end IS NULL THEN NULL ELSE governed_timestamp_v1(p.window_end) END IS CASE WHEN NEW.window_end IS NULL THEN NULL ELSE governed_timestamp_v1(NEW.window_end) END) THEN RAISE(ABORT,'sealed batch requires exact finalized protected intake') END;
END;
DROP TRIGGER governed_batch_item_insert;
CREATE TRIGGER governed_batch_item_insert BEFORE INSERT ON governed_review_batch_items BEGIN
 SELECT CASE WHEN NEW.created_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_batches b JOIN governed_review_items i ON i.project_id=b.project_id AND i.id=NEW.review_item_id WHERE b.project_id=NEW.project_id AND b.id=NEW.batch_id AND b.created_command_token=sqlite_command_token() AND NOT EXISTS(SELECT 1 FROM governed_review_batch_finalizations WHERE batch_id=b.id) AND ((b.source_population_kind='dataset_revision' AND i.source_kind='dataset_revision_item' AND i.source_revision_id=b.source_population_id) OR (b.source_population_kind='sealed_intake' AND i.source_kind='sealed_intake' AND i.sealed_intake_population_id=b.source_population_id AND i.created_by_subject_id=b.custodian_subject_id)) AND i.content_digest=NEW.frame_member_digest AND NEW.serve_position<b.fixed_budget AND NEW.draw_position<b.fixed_budget AND (b.selection_method<>'stratified_random' OR NEW.stratum_key IS NOT NULL) AND (b.selection_method NOT IN('simple_random','stratified_random') OR (NEW.inclusion_probability IS NOT NULL AND NEW.sampling_weight IS NOT NULL))) THEN RAISE(ABORT,'batch item requires exact source and unfinalized owning command') END;
 SELECT CASE WHEN (NEW.inclusion_probability IS NOT NULL AND governed_positive_numeric_v1(NEW.inclusion_probability,1)<>1) OR (NEW.sampling_weight IS NOT NULL AND governed_positive_numeric_v1(NEW.sampling_weight,0)<>1) THEN RAISE(ABORT,'invalid governed sampling numbers') END;
 SELECT CASE WHEN NEW.content_digest IS NOT governed_content_v1_digest('governed-review-batch-item/v1',json_object('batchId',NEW.batch_id,'drawPosition',NEW.draw_position,'frameMemberDigest',NEW.frame_member_digest,'inclusionProbability',json(NEW.inclusion_probability),'reviewItemId',NEW.review_item_id,'samplingWeight',json(NEW.sampling_weight),'servePosition',NEW.serve_position,'stratumKey',NEW.stratum_key)) THEN RAISE(ABORT,'governed draft content digest mismatch') END;
END;
