-- Sealed truth remains a same-command exact native bundle with protected lineage.
DROP TRIGGER dataset_revision_stage;
CREATE TRIGGER dataset_revision_stage BEFORE INSERT ON dataset_revisions WHEN NOT(
 (NEW.role='sealed_validation' AND NEW.source_kind='sealed_intake' AND NEW.analysis_population_id IS NULL AND NEW.source_dataset_id IS NULL AND NEW.criterion_version_id IS NOT NULL AND NEW.provenance_level='governed_blind')
 OR (NEW.analysis_population_id IS NULL AND ((NEW.role IN ('analysis_authoring','iterative_development') AND NEW.source_kind='collection_snapshot') OR (NEW.role='regression_golden' AND NEW.source_kind='golden_snapshot')))
 OR (NEW.source_kind='analysis_population' AND NEW.role='analysis_authoring' AND EXISTS(
 SELECT 1 FROM analysis_populations p WHERE p.project_id=NEW.project_id AND p.id=NEW.analysis_population_id AND p.dataset_revision_id=NEW.id AND p.created_command_token=sqlite_command_token()
 AND NEW.series_id='analysis-population:'||p.id AND NEW.revision_number=1 AND NEW.source_dataset_id IS NULL AND NEW.parent_revision_id IS NULL AND NEW.criterion_version_id IS NULL
 AND NEW.provenance_level='unverified' AND NEW.created_by_user_id=p.created_by_user_id AND NEW.created_at=p.created_at AND NEW.item_count=p.population_size)))
BEGIN SELECT RAISE(ABORT,'governed dataset revision workflow unavailable or population mismatch'); END;
CREATE UNIQUE INDEX dataset_revision_one_sealed_child ON dataset_revisions(parent_revision_id) WHERE parent_revision_id IS NOT NULL AND role='sealed_validation';
CREATE TRIGGER dataset_revision_protected_parent BEFORE INSERT ON dataset_revisions WHEN NEW.parent_revision_id IS NOT NULL BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM dataset_revisions WHERE id=NEW.parent_revision_id AND source_kind='analysis_population') THEN RAISE(ABORT,'analysis population revisions cannot have successors') END;
 SELECT CASE WHEN NEW.role='sealed_validation' AND (NOT EXISTS(SELECT 1 FROM dataset_revisions WHERE id=NEW.parent_revision_id AND role='sealed_validation') OR EXISTS(SELECT 1 FROM dataset_exposure_events WHERE revision_id=NEW.parent_revision_id AND exposure_class='development') OR EXISTS(SELECT 1 FROM dataset_revisions WHERE parent_revision_id=NEW.parent_revision_id AND role='sealed_validation')) THEN RAISE(ABORT,'sealed successor requires protected sealed predecessor without child') END;
 SELECT CASE WHEN NEW.role<>'sealed_validation' AND EXISTS(SELECT 1 FROM dataset_revisions WHERE id=NEW.parent_revision_id AND role='sealed_validation') AND NOT EXISTS(SELECT 1 FROM dataset_exposure_events WHERE revision_id=NEW.parent_revision_id AND kind='declassification' AND exposure_class='development') THEN RAISE(ABORT,'sealed to nonsealed transition requires recorded declassification') END;
END;
DROP TRIGGER governed_truth_insert;
CREATE TRIGGER governed_truth_insert BEFORE INSERT ON governed_dataset_truth_links BEGIN
 SELECT CASE WHEN NEW.created_at IS NOT sqlite_command_time() OR NEW.created_command_token IS NOT sqlite_command_token() OR EXISTS(SELECT 1 FROM dataset_revision_finalizations WHERE revision_id=NEW.dataset_revision_id) THEN RAISE(ABORT,'truth link requires current unfinalized revision command') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM dataset_revisions r JOIN dataset_revision_items i ON i.revision_id=r.id AND i.project_id=r.project_id WHERE r.id=NEW.dataset_revision_id AND r.project_id=NEW.project_id AND i.id=NEW.dataset_revision_item_id AND r.criterion_version_id=NEW.criterion_version_id AND i.reference_label=NEW.resolved_label AND json_extract(i.reference_provenance,'$.kind')='dataset_claim' AND json_extract(i.reference_provenance,'$.sourceId')=NEW.id) THEN RAISE(ABORT,'truth link requires exact revision item criterion label and compatibility pointer') END;
 SELECT CASE WHEN json_array_length(NEW.governed_label_ids)>20 OR EXISTS(SELECT 1 FROM json_each(NEW.governed_label_ids) WHERE type<>'text' OR length(value)=0 OR length(CAST(value AS BLOB))>256) OR (SELECT coalesce(sum(length(CAST(value AS BLOB))),0) FROM json_each(NEW.governed_label_ids))>4096 THEN RAISE(ABORT,'invalid truth label ids') END;
 SELECT CASE WHEN NEW.source_kind IN('governed_labels','adjudication') AND NOT EXISTS(SELECT 1 FROM governed_review_batch_items bi JOIN governed_review_batches b ON b.id=bi.batch_id JOIN governed_review_batch_states bs ON bs.batch_id=b.id JOIN governed_review_items ri ON ri.id=bi.review_item_id JOIN governed_review_item_resolutions res ON res.batch_item_id=bi.id JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id JOIN dataset_revision_items i ON i.id=NEW.dataset_revision_item_id WHERE bi.id=NEW.batch_item_id AND b.project_id=NEW.project_id AND b.criterion_version_id=NEW.criterion_version_id AND bs.state='resolved' AND r.role=b.role_intent AND (b.role_intent<>'sealed_validation' OR (ri.source_kind='sealed_intake' AND r.source_kind='sealed_intake' AND r.parent_revision_id IS ri.sealed_predecessor_revision_id)) AND r.provenance_level='governed_blind' AND i.input_digest=ri.input_digest AND governed_canonical_json_v1(i.payload_snapshot)=governed_canonical_json_v1(ri.review_payload_snapshot) AND res.resolution_kind=NEW.resolution_kind AND res.resolved_label=NEW.resolved_label AND res.adjudication_id IS NEW.adjudication_id) THEN RAISE(ABORT,'native truth requires exact resolved batch evidence') END;
 SELECT CASE WHEN NEW.source_kind='governed_labels' AND (NEW.supporting_label_count<>json_array_length(NEW.governed_label_ids) OR NEW.supporting_label_count<>(SELECT required_labels_per_item FROM governed_review_batches b JOIN governed_review_batch_items i ON i.batch_id=b.id WHERE i.id=NEW.batch_item_id) OR NEW.governed_label_ids IS NOT (SELECT json_group_array(label_id ORDER BY label_id) FROM governed_active_review_labels WHERE batch_item_id=NEW.batch_item_id)) THEN RAISE(ABORT,'truth must name every exact active independent label') END;
 SELECT CASE WHEN NEW.source_kind='adjudication' AND NOT EXISTS(SELECT 1 FROM governed_review_adjudications a WHERE a.id=NEW.adjudication_id AND a.batch_item_id=NEW.batch_item_id AND a.decision=NEW.resolved_label AND a.considered_label_count=NEW.supporting_label_count) THEN RAISE(ABORT,'truth requires exact authoritative adjudication') END;
 SELECT CASE WHEN NEW.source_kind='imported_truth' AND NOT EXISTS(SELECT 1 FROM governed_imported_truth t JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id JOIN dataset_revision_items i ON i.id=NEW.dataset_revision_item_id WHERE t.id=NEW.imported_truth_id AND r.role IN('analysis_authoring','iterative_development') AND r.source_kind='collection_snapshot' AND t.project_id=NEW.project_id AND t.criterion_version_id=NEW.criterion_version_id AND t.input_digest=i.input_digest AND governed_canonical_json_v1(t.payload_snapshot)=governed_canonical_json_v1(i.payload_snapshot) AND t.label=NEW.resolved_label AND NEW.resolution_kind=CASE t.evidence_class WHEN 'imported_self_attested' THEN 'imported_self_attested' WHEN 'imported_verified_attested' THEN 'imported_verified_attested' ELSE 'imported_unverified' END AND r.provenance_level=CASE t.evidence_class WHEN 'imported_self_attested' THEN 'imported_self_attested' WHEN 'imported_verified_attested' THEN 'imported_verified_attested' ELSE 'unverified' END) THEN RAISE(ABORT,'imported truth must preserve exact artifact and honest provenance') END;
 SELECT CASE WHEN NEW.content_digest IS NOT governed_content_v1_digest('governed-dataset-truth-link/v1',json_object('adjudicationId',NEW.adjudication_id,'batchItemId',NEW.batch_item_id,'criterionVersionId',NEW.criterion_version_id,'datasetRevisionId',NEW.dataset_revision_id,'datasetRevisionItemId',NEW.dataset_revision_item_id,'governedLabelIds',json(NEW.governed_label_ids),'importedTruthId',NEW.imported_truth_id,'resolutionKind',NEW.resolution_kind,'resolvedLabel',NEW.resolved_label,'sourceKind',NEW.source_kind,'supportingLabelCount',NEW.supporting_label_count)) THEN RAISE(ABORT,'truth content digest mismatch') END;
END;
DROP TRIGGER governed_batch_event_insert;
CREATE TRIGGER governed_batch_event_insert BEFORE INSERT ON governed_review_batch_events BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_batches b WHERE b.id=NEW.batch_id AND b.project_id=NEW.project_id AND b.created_at<=NEW.occurred_at AND EXISTS(SELECT 1 FROM governed_review_batch_finalizations WHERE batch_id=b.id)) THEN RAISE(ABORT,'batch event requires current owning command and finalized draft') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_reviewer_subjects s JOIN project_members pm ON pm.project_id=s.project_id AND pm.user_id=s.account_user_id WHERE s.project_id=NEW.project_id AND s.id=NEW.actor_subject_id AND pm.role='owner' AND NEW.actor_role_at_review='owner') THEN RAISE(ABORT,'batch transition requires live owner') END;
 SELECT CASE WHEN NEW.expected_previous_state_version<>(SELECT state_version FROM governed_review_batch_states WHERE batch_id=NEW.batch_id) OR NEW.state_version<>NEW.expected_previous_state_version+1 OR NEW.sequence<>NEW.state_version OR NEW.previous_event_digest IS NOT (SELECT event_digest FROM governed_review_batch_events WHERE batch_id=NEW.batch_id ORDER BY state_version DESC LIMIT 1) THEN RAISE(ABORT,'governed batch state version conflict') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_batch_states WHERE batch_id=NEW.batch_id AND ((state='draft' AND NEW.event_kind IN('open','abandoned')) OR (state='open' AND NEW.event_kind IN('abandoned','labeling_closed')) OR (state='labeling_closed' AND NEW.event_kind IN('alignment_open','adjudicating','resolved','incomplete')) OR (state='alignment_open' AND NEW.event_kind IN('adjudicating','incomplete')) OR (state='adjudicating' AND NEW.event_kind IN('resolved','incomplete')) OR (state='resolved' AND NEW.event_kind='frozen'))) THEN RAISE(ABORT,'invalid governed batch transition') END;
 SELECT CASE WHEN (NEW.event_kind<>'frozen' AND (NEW.dataset_revision_id IS NOT NULL OR NEW.representative_of_population_id IS NOT NULL OR json_array_length(NEW.representative_ineligible_reasons)<>0)) OR governed_jsonb_octets_v1(NEW.details)>65536 THEN RAISE(ABORT,'invalid pre-barrier batch details') END;
 INSERT INTO governed_review_task_events(id,project_id,task_id,sequence,state_version,expected_previous_state_version,event_kind,reason,previous_event_digest,event_digest,idempotency_key,request_digest,occurred_at)
 SELECT 'grte_expired_'||NEW.id||'_'||t.id,t.project_id,t.id,ts.state_version+1,ts.state_version+1,ts.state_version,'expired','fixed_stop',e.event_digest,
 governed_content_v1_digest('governed-review-task-event/v1',json_object('activity',NULL,'actorRoleAtReview',NULL,'actorSubjectId',NULL,'canonicalizationVersion',NULL,'eventKind','expired','exposureClass',NULL,'labelId',NULL,'canonicalViewBytesBase64',NULL,'previousEventDigest',e.event_digest,'reason','fixed_stop','sequence',ts.state_version+1,'stateVersion',ts.state_version+1,'taskId',t.id,'viewContractVersion',NULL,'viewDigest',NULL)),
 'expire:'||NEW.id,governed_content_v1_digest('governed-review-expiry-request/v1',json_object('batchEventId',NEW.id,'taskId',t.id)),NEW.occurred_at
 FROM governed_review_tasks t JOIN governed_review_task_states ts ON ts.task_id=t.id JOIN governed_review_batches b ON b.id=t.batch_id LEFT JOIN governed_review_task_events e ON e.task_id=t.id AND e.state_version=ts.state_version
 WHERE t.batch_id=NEW.batch_id AND NEW.event_kind='labeling_closed' AND governed_timestamp_v1(NEW.occurred_at)>=governed_timestamp_v1(b.stop_at) AND ts.state IN('assigned','viewed','withdrawn') ORDER BY t.id;
 SELECT CASE WHEN NEW.event_kind='labeling_closed' AND EXISTS(SELECT 1 FROM governed_review_task_states WHERE batch_id=NEW.batch_id AND state NOT IN('submitted','deferred','expired')) THEN RAISE(ABORT,'labeling closure requires terminal tasks or fixed stop') END;
 SELECT CASE WHEN NEW.event_kind='resolved' AND EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind NOT IN('single_rater','unanimous','adjudicated')) THEN RAISE(ABORT,'batch resolution requires complete resolved truth') END;
 SELECT CASE WHEN NEW.event_kind='incomplete' AND NOT EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind IN('coverage_gap','unresolvable')) THEN RAISE(ABORT,'incomplete requires coverage gap or unresolvable adjudication') END;
 SELECT CASE WHEN NEW.event_kind IN('alignment_open','adjudicating') AND (EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind='coverage_gap') OR NOT EXISTS(SELECT 1 FROM governed_review_item_resolutions WHERE batch_id=NEW.batch_id AND resolution_kind='conflict')) THEN RAISE(ABORT,'alignment and adjudication require complete coverage and conflict') END;
 SELECT CASE WHEN NEW.event_kind='adjudicating' AND (SELECT state FROM governed_review_batch_states WHERE batch_id=NEW.batch_id)='alignment_open' AND NOT EXISTS(SELECT 1 FROM governed_review_alignment_events WHERE batch_id=NEW.batch_id AND event_kind='closed' AND sequence=(SELECT max(sequence) FROM governed_review_alignment_events WHERE batch_id=NEW.batch_id)) THEN RAISE(ABORT,'alignment must close before adjudication') END;
 SELECT CASE WHEN NEW.event_kind='frozen' AND NOT EXISTS(SELECT 1 FROM governed_review_batches b JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id AND r.project_id=b.project_id WHERE b.id=NEW.batch_id AND r.criterion_version_id=b.criterion_version_id AND r.role=b.role_intent AND r.item_count=b.fixed_budget AND r.provenance_level='governed_blind' AND r.created_at=sqlite_command_time() AND r.source_kind=CASE b.role_intent WHEN 'sealed_validation' THEN 'sealed_intake' ELSE 'collection_snapshot' END AND NOT EXISTS(SELECT 1 FROM dataset_revision_finalizations WHERE revision_id=r.id) AND (SELECT count(*) FROM governed_dataset_truth_links WHERE dataset_revision_id=r.id)=b.fixed_budget AND NOT EXISTS(SELECT 1 FROM governed_review_batch_items i WHERE i.batch_id=b.id AND (SELECT count(*) FROM governed_dataset_truth_links t WHERE t.batch_item_id=i.id AND t.dataset_revision_id=r.id AND t.created_command_token=sqlite_command_token())<>1)) THEN RAISE(ABORT,'freeze requires complete exact same-command native truth revision') END;
 SELECT CASE WHEN NEW.event_kind='frozen' AND (governed_canonical_json_v1(NEW.representative_ineligible_reasons) IS NOT governed_canonical_json_v1((SELECT json_group_array(reason ORDER BY reason) FROM governed_review_representative_reasons WHERE batch_id=NEW.batch_id)) OR NEW.representative_of_population_id IS NOT (SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_representative_reasons WHERE batch_id=b.id) THEN b.population_id ELSE NULL END FROM governed_review_batches b WHERE b.id=NEW.batch_id)) THEN RAISE(ABORT,'freeze representative scope must match retained evidence') END;
 SELECT CASE WHEN NEW.event_digest IS NOT governed_content_v1_digest('governed-review-batch-event/v1',json_object('actorRoleAtReview',NEW.actor_role_at_review,'actorSubjectId',NEW.actor_subject_id,'batchId',NEW.batch_id,'datasetRevisionId',NEW.dataset_revision_id,'details',json(NEW.details),'eventKind',NEW.event_kind,'previousEventDigest',NEW.previous_event_digest,'representativeIneligibleReasons',json(NEW.representative_ineligible_reasons),'representativeOfPopulationId',NEW.representative_of_population_id,'sequence',NEW.sequence,'stateVersion',NEW.state_version)) THEN RAISE(ABORT,'governed stream event digest mismatch') END;
END;
CREATE TRIGGER governed_sealed_truth_access BEFORE INSERT ON governed_review_batch_events WHEN NEW.event_kind='frozen' AND EXISTS(SELECT 1 FROM governed_review_batches WHERE id=NEW.batch_id AND role_intent='sealed_validation') BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM (
 SELECT custodian_subject_id subject_id FROM governed_review_batches WHERE id=NEW.batch_id
 UNION SELECT reviewer_subject_id FROM governed_review_tasks WHERE batch_id=NEW.batch_id
 UNION SELECT adjudicator_subject_id FROM governed_review_adjudications WHERE batch_id=NEW.batch_id
 UNION SELECT subject_id FROM governed_review_capability_checks WHERE batch_id=NEW.batch_id AND check_scope='adjudication' AND result='eligible'
 ) exposed WHERE NOT analysis_governed_separation_valid_v1(NEW.batch_id,'truth_freeze',subject_id)) THEN RAISE(ABORT,'sealed truth requires live eligible checks for all exposed subjects') END;
END;
