-- Exact full-frame handoff from an already committed promotion; no evaluator or truth claim.
DROP TRIGGER governed_batch_source_stage;
CREATE TRIGGER analysis_promotion_handoff_insert BEFORE INSERT ON governed_review_batches WHEN NEW.source_population_kind='analysis_promotion_handoff' BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM analysis_criterion_promotions p JOIN analysis_promotion_finalizations f ON f.promotion_id=p.id JOIN dataset_revisions r ON r.id=p.source_dataset_revision_id AND r.project_id=p.project_id WHERE p.id=NEW.source_population_id AND p.project_id=NEW.project_id AND p.created_command_token<>sqlite_command_token()
 AND NEW.role_intent='analysis_authoring' AND NEW.criterion_version_id=p.criterion_version_id AND NEW.population_id=p.source_dataset_revision_id AND r.role='analysis_authoring' AND r.source_kind='analysis_population'
 AND NEW.population_digest=p.source_dataset_revision_content_digest AND NEW.population_size=r.item_count
 AND NEW.window_start IS NULL AND NEW.window_end IS NULL AND NEW.evaluator_blind=1 AND NEW.peer_blind_until_labeling_closed=1 AND NEW.separation_of_duties_required=0 AND NEW.custodian_subject_id IS NULL AND NEW.custodian_role_at_review IS NULL
 AND governed_canonical_json_v1(NEW.population_definition)=governed_canonical_json_v1(json_object('criterionVersionId',p.criterion_version_id,'handoffDigest',p.handoff_digest,'kind','analysis_promotion_handoff','promotionId',p.id,'sourceDatasetRevisionId',p.source_dataset_revision_id))
 AND governed_canonical_json_v1(NEW.population_collection_provenance)=governed_canonical_json_v1(json_object('createsEvaluator',json('false'),'createsTruth',json('false'),'evidenceClass','development_authoring_not_truth','handoffDigest',p.handoff_digest,'kind','analysis_promotion_handoff','promotionId',p.id,'provenanceLevel',r.provenance_level,'revisionDigest',p.source_dataset_revision_digest,'sourceKind','analysis_population')))
 THEN RAISE(ABORT,'batch requires exact previously committed full-frame promotion handoff') END;
END;
DROP TRIGGER governed_batch_item_insert;
CREATE TRIGGER governed_batch_item_insert BEFORE INSERT ON governed_review_batch_items BEGIN
 SELECT CASE WHEN NEW.created_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM governed_review_batches b JOIN governed_review_items i ON i.project_id=b.project_id AND i.id=NEW.review_item_id WHERE b.project_id=NEW.project_id AND b.id=NEW.batch_id AND b.created_command_token=sqlite_command_token() AND NOT EXISTS(SELECT 1 FROM governed_review_batch_finalizations WHERE batch_id=b.id) AND ((b.source_population_kind='analysis_promotion_handoff' AND i.source_kind='dataset_revision_item' AND i.source_revision_id=b.population_id) OR (b.source_population_kind='dataset_revision' AND i.source_kind='dataset_revision_item' AND i.source_revision_id=b.source_population_id) OR (b.source_population_kind='sealed_intake' AND i.source_kind='sealed_intake' AND i.sealed_intake_population_id=b.source_population_id AND i.created_by_subject_id=b.custodian_subject_id)) AND i.content_digest=NEW.frame_member_digest AND NEW.serve_position<b.fixed_budget AND NEW.draw_position<b.fixed_budget AND (b.selection_method<>'stratified_random' OR NEW.stratum_key IS NOT NULL) AND (b.selection_method NOT IN('simple_random','stratified_random') OR (NEW.inclusion_probability IS NOT NULL AND NEW.sampling_weight IS NOT NULL))) THEN RAISE(ABORT,'batch item requires exact source and unfinalized owning command') END;
 SELECT CASE WHEN (NEW.inclusion_probability IS NOT NULL AND governed_positive_numeric_v1(NEW.inclusion_probability,1)<>1) OR (NEW.sampling_weight IS NOT NULL AND governed_positive_numeric_v1(NEW.sampling_weight,0)<>1) THEN RAISE(ABORT,'invalid governed sampling numbers') END;
 SELECT CASE WHEN NEW.content_digest IS NOT governed_content_v1_digest('governed-review-batch-item/v1',json_object('batchId',NEW.batch_id,'drawPosition',NEW.draw_position,'frameMemberDigest',NEW.frame_member_digest,'inclusionProbability',json(NEW.inclusion_probability),'reviewItemId',NEW.review_item_id,'samplingWeight',json(NEW.sampling_weight),'servePosition',NEW.serve_position,'stratumKey',NEW.stratum_key)) THEN RAISE(ABORT,'governed draft content digest mismatch') END;
END;
