-- Calibration storage domains from PostgreSQL. Provider dispatch and terminal
-- evidence writes remain staged until the complete owning commands are installed.
CREATE TABLE binary_calibration_runs (
 id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 dataset_revision_id TEXT NOT NULL,
 revision_digest TEXT NOT NULL,
 truth_content_digest TEXT NOT NULL,
 item_count INTEGER NOT NULL,
 criterion_id TEXT NOT NULL,
 criterion_version_id TEXT NOT NULL,
 criterion_digest TEXT NOT NULL,
 skill_id TEXT NOT NULL,
 skill_version_id TEXT NOT NULL,
 skill_digest TEXT NOT NULL,
 output_contract_digest TEXT NOT NULL,
 requested_provider TEXT NOT NULL,
 definition_digest TEXT NOT NULL,
 execution_binding TEXT NOT NULL,
 requested_binding_digest TEXT NOT NULL,
 suite_manifest_id TEXT,
 suite_manifest_digest TEXT,
 suite_member_position INTEGER,
 governed_review_batch_id TEXT NOT NULL,
 governed_review_batch_digest TEXT NOT NULL,
 review_instruction_version_id TEXT NOT NULL,
 review_instruction_digest TEXT NOT NULL,
 population_id TEXT NOT NULL,
 population_digest TEXT NOT NULL,
 draw_digest TEXT NOT NULL,
 representative_of_population_id TEXT,
 representative_ineligible_reasons TEXT NOT NULL DEFAULT '[]',
 selection_method TEXT NOT NULL,
 positive_class TEXT NOT NULL,
 trial_plan_kind TEXT NOT NULL,
 trials_per_item INTEGER NOT NULL,
 execution_environment TEXT NOT NULL,
 provider_policy_id TEXT NOT NULL,
 provider_policy_digest TEXT NOT NULL,
 provider_policy_canonical_bytes BLOB NOT NULL,
 payload_transmission TEXT NOT NULL,
 idempotency_key TEXT NOT NULL,
 request_digest TEXT NOT NULL,
 state TEXT NOT NULL,
 planned_observations INTEGER NOT NULL,
 accounted_observations INTEGER NOT NULL DEFAULT 0,
 claim_worker_id TEXT,
 claim_token TEXT,
 claim_expires_at TEXT,
 authorization_check_id TEXT,
 completion_check_id TEXT,
 artifact_id TEXT,
 artifact_digest TEXT,
 evidence_digest TEXT,
 rejection_reason TEXT,
 started_at TEXT,
 completed_at TEXT,
 created_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(project_id,idempotency_key),
 FOREIGN KEY(project_id,dataset_revision_id) REFERENCES dataset_revisions(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,criterion_id) REFERENCES criteria(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,criterion_version_id) REFERENCES criterion_versions(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,skill_id) REFERENCES skills(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,skill_version_id) REFERENCES skill_versions(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,governed_review_batch_id) REFERENCES governed_review_batches(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,review_instruction_version_id) REFERENCES review_instruction_versions(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,suite_manifest_id) REFERENCES evaluator_suite_manifests(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK(length(revision_digest)=71 AND substr(revision_digest,1,7)='sha256:' AND substr(revision_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(truth_content_digest)=71 AND substr(truth_content_digest,1,7)='sha256:' AND substr(truth_content_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(criterion_digest)=71 AND substr(criterion_digest,1,7)='sha256:' AND substr(criterion_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(skill_digest)=71 AND substr(skill_digest,1,7)='sha256:' AND substr(skill_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(output_contract_digest)=71 AND substr(output_contract_digest,1,7)='sha256:' AND substr(output_contract_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(definition_digest)=71 AND substr(definition_digest,1,7)='sha256:' AND substr(definition_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(json_valid(execution_binding)),
 CHECK(length(requested_binding_digest)=71 AND substr(requested_binding_digest,1,7)='sha256:' AND substr(requested_binding_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(suite_manifest_digest)=71 AND substr(suite_manifest_digest,1,7)='sha256:' AND substr(suite_manifest_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(governed_review_batch_digest)=71 AND substr(governed_review_batch_digest,1,7)='sha256:' AND substr(governed_review_batch_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(review_instruction_digest)=71 AND substr(review_instruction_digest,1,7)='sha256:' AND substr(review_instruction_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(population_digest)=71 AND substr(population_digest,1,7)='sha256:' AND substr(population_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(draw_digest)=71 AND substr(draw_digest,1,7)='sha256:' AND substr(draw_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(json_valid(representative_ineligible_reasons) AND json_type(representative_ineligible_reasons)='array'),
 CHECK(length(provider_policy_digest)=71 AND substr(provider_policy_digest,1,7)='sha256:' AND substr(provider_policy_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(request_digest)=71 AND substr(request_digest,1,7)='sha256:' AND substr(request_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(artifact_digest)=71 AND substr(artifact_digest,1,7)='sha256:' AND substr(artifact_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(evidence_digest)=71 AND substr(evidence_digest,1,7)='sha256:' AND substr(evidence_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK (((accounted_observations >= 0) AND (accounted_observations <= planned_observations))),
 CHECK ((requested_provider = (execution_binding ->> 'provider'))),
 CHECK ((((suite_manifest_id IS NULL) AND (suite_manifest_digest IS NULL) AND (suite_member_position IS NULL)) OR ((suite_manifest_id IS NOT NULL) AND (suite_manifest_digest IS NOT NULL) AND (suite_member_position IS NOT NULL)))),
 CHECK (((representative_of_population_id IS NULL) <> (json_array_length(representative_ineligible_reasons) = 0))),
 CHECK (((claim_token IS NOT NULL) OR ((claim_worker_id IS NULL) AND (claim_expires_at IS NULL)))),
 CHECK (((claim_token IS NULL) OR ((claim_worker_id IS NOT NULL) AND (claim_expires_at IS NOT NULL)))),
 CHECK (((state NOT IN ('complete', 'incomplete', 'rejected')) OR (completed_at IS NOT NULL))),
 CHECK (((state NOT IN ('complete', 'incomplete')) OR ((artifact_id IS NOT NULL) AND (artifact_digest IS NOT NULL) AND (evidence_digest IS NOT NULL)))),
 CHECK (((state <> 'rejected') OR (rejection_reason IS NOT NULL))),
 CHECK ((execution_environment IN ('external_provider', 'self_hosted_provider', 'local_provider'))),
 CHECK ((length(idempotency_key) BETWEEN 1 AND 200) AND (idempotency_key = trim(idempotency_key))),
 CHECK (((item_count >= 1) AND (item_count <= 5000))),
 CHECK ((payload_transmission = 'sealed_payload_to_pinned_provider')),
 CHECK (((planned_observations >= 1) AND (planned_observations <= 5000))),
 CHECK (((length(population_id) > 0) AND (length(CAST(population_id AS BLOB)) <= 4096))),
 CHECK ((positive_class IN ('pass', 'fail'))),
 CHECK (((length(provider_policy_canonical_bytes) >= 2) AND (length(provider_policy_canonical_bytes) <= 65536))),
 CHECK (((length(provider_policy_id) > 0) AND (length(CAST(provider_policy_id AS BLOB)) <= 4096))),
 CHECK (((length(requested_provider) > 0) AND (length(requested_provider) <= 4096) AND (length(CAST(requested_provider AS BLOB)) <= 16384))),
 CHECK ((selection_method IN ('simple_random', 'systematic', 'stratified_random', 'convenience', 'uncertainty', 'failure_hunting', 'manual'))),
 CHECK ((state IN ('queued', 'running', 'recovery_required', 'complete', 'incomplete', 'rejected'))),
 CHECK (((suite_member_position >= 0) AND (suite_member_position <= 99))),
 CHECK ((trial_plan_kind = 'single')),
 CHECK ((trials_per_item = 1))
) STRICT;
CREATE TRIGGER binary_calibration_runs_erase BEFORE DELETE ON binary_calibration_runs WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TABLE binary_calibration_attempts (
 id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 dataset_revision_item_id TEXT NOT NULL,
 dataset_revision_item_digest TEXT NOT NULL,
 trial_index INTEGER NOT NULL,
 truth_label TEXT NOT NULL,
 accounting_state TEXT NOT NULL DEFAULT 'pending',
 attempt_state TEXT NOT NULL DEFAULT 'not_started',
 terminal_evaluator_outcome TEXT,
 error_code TEXT,
 physical_provider_calls INTEGER NOT NULL DEFAULT 0,
 provider TEXT NOT NULL,
 observed_model TEXT,
 observed_version TEXT,
 system_fingerprint TEXT,
 upstream_provider TEXT,
 commitment_salt TEXT NOT NULL,
 accounted_at TEXT,
 created_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(run_id,dataset_revision_item_id,trial_index),
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,dataset_revision_item_id) REFERENCES dataset_revision_items(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK(length(dataset_revision_item_digest)=71 AND substr(dataset_revision_item_digest,1,7)='sha256:' AND substr(dataset_revision_item_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK ((accounting_state IN ('pending', 'accounted'))),
 CHECK ((attempt_state IN ('not_started', 'started', 'terminal'))),
 CHECK ((((accounting_state = 'pending') AND (terminal_evaluator_outcome IS NULL) AND (error_code IS NULL) AND (accounted_at IS NULL)) OR ((accounting_state = 'accounted') AND (terminal_evaluator_outcome IS NOT NULL) AND (accounted_at IS NOT NULL)))),
 CHECK (((error_code IS NULL) OR (terminal_evaluator_outcome = 'errored'))),
 CHECK (((terminal_evaluator_outcome <> 'errored') OR (error_code IS NOT NULL))),
 CHECK (((terminal_evaluator_outcome IS NULL) OR ((terminal_evaluator_outcome IN ('evaluator_pass', 'evaluator_fail', 'abstained')) AND (attempt_state = 'terminal') AND (physical_provider_calls >= 1) AND (error_code IS NULL)) OR ((terminal_evaluator_outcome = 'not_attempted') AND (attempt_state = 'not_started') AND (physical_provider_calls = 0) AND (error_code IS NULL)) OR ((terminal_evaluator_outcome = 'errored') AND (error_code = 'outcome_unknown') AND (attempt_state = 'started') AND (physical_provider_calls >= 1)) OR ((terminal_evaluator_outcome = 'errored') AND (error_code <> 'outcome_unknown') AND (attempt_state = 'terminal')))),
 CHECK (((physical_provider_calls > 0) OR ((observed_model IS NULL) AND (observed_version IS NULL) AND (system_fingerprint IS NULL) AND (upstream_provider IS NULL)))),
 CHECK ((((observed_version IS NULL) AND (system_fingerprint IS NULL)) OR (observed_model IS NOT NULL))),
 CHECK (((attempt_state <> 'not_started') OR ((physical_provider_calls = 0) AND (observed_model IS NULL) AND (observed_version IS NULL) AND (system_fingerprint IS NULL) AND (upstream_provider IS NULL)))),
 CHECK(length(commitment_salt)=64 AND commitment_salt NOT GLOB '*[^0-9a-f]*'),
 CHECK ((error_code IN ('provider_rejected_request', 'provider_unavailable', 'provider_authentication', 'provider_rate_limit', 'provider_timeout', 'provider_transport', 'provider_protocol', 'invalid_evaluator_output', 'outcome_unknown', 'internal'))),
 CHECK (((length(observed_model) <= 4096) AND (length(CAST(observed_model AS BLOB)) <= 16384))),
 CHECK (((length(observed_version) <= 4096) AND (length(CAST(observed_version AS BLOB)) <= 16384))),
 CHECK (((physical_provider_calls >= 0) AND (physical_provider_calls <= '9007199254740991'))),
 CHECK (((length(provider) > 0) AND (length(provider) <= 4096) AND (length(CAST(provider AS BLOB)) <= 16384))),
 CHECK (((length(system_fingerprint) <= 4096) AND (length(CAST(system_fingerprint AS BLOB)) <= 16384))),
 CHECK ((terminal_evaluator_outcome IN ('evaluator_pass', 'evaluator_fail', 'abstained', 'errored', 'not_attempted'))),
 CHECK ((trial_index = 0)),
 CHECK ((truth_label IN ('pass', 'fail'))),
 CHECK (((length(upstream_provider) > 0) AND (length(upstream_provider) <= 4096) AND (length(CAST(upstream_provider AS BLOB)) <= 16384)))
) STRICT;
CREATE TRIGGER binary_calibration_attempts_erase BEFORE DELETE ON binary_calibration_attempts WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_attempts_stage BEFORE INSERT ON binary_calibration_attempts BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TABLE binary_calibration_exposure_checks (
 id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 phase TEXT NOT NULL,
 exposure_state TEXT NOT NULL,
 eligibility_result TEXT NOT NULL,
 eligibility_reasons TEXT NOT NULL DEFAULT '[]',
 canonical_bytes BLOB NOT NULL,
 snapshot_digest TEXT NOT NULL,
 recorded_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(run_id,phase),
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK(json_valid(eligibility_reasons) AND json_type(eligibility_reasons)='array'),
 CHECK(length(snapshot_digest)=71 AND substr(snapshot_digest,1,7)='sha256:' AND substr(snapshot_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK (((length(canonical_bytes) >= 2) AND (length(canonical_bytes) <= 4194304))),
 CHECK (((eligibility_result = 'eligible') = (json_array_length(eligibility_reasons) = 0))),
 CHECK (((phase <> 'authorization') OR ((exposure_state = 'protected') AND (eligibility_result = 'eligible')))),
 CHECK ((eligibility_result IN ('eligible', 'ineligible'))),
 CHECK ((exposure_state IN ('protected', 'exposed'))),
 CHECK ((phase IN ('authorization', 'completion')))
) STRICT;
CREATE TRIGGER binary_calibration_exposure_checks_immutable BEFORE UPDATE ON binary_calibration_exposure_checks BEGIN SELECT RAISE(ABORT,'immutable calibration evidence'); END;
CREATE TRIGGER binary_calibration_exposure_checks_erase BEFORE DELETE ON binary_calibration_exposure_checks WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_exposure_checks_stage BEFORE INSERT ON binary_calibration_exposure_checks BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TABLE binary_calibration_private_ledgers (
 id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 artifact_id TEXT NOT NULL,
 contract TEXT NOT NULL,
 canonical_bytes BLOB NOT NULL,
 commitment_digest TEXT NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(run_id),
 UNIQUE(artifact_id),
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,artifact_id) REFERENCES binary_calibration_artifacts(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK(length(commitment_digest)=71 AND substr(commitment_digest,1,7)='sha256:' AND substr(commitment_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK (((length(canonical_bytes) >= 2) AND (length(canonical_bytes) <= 16777216))),
 CHECK ((contract = 'rubrist/binary-calibration-private-ledger/v1'))
) STRICT;
CREATE TRIGGER binary_calibration_private_ledgers_immutable BEFORE UPDATE ON binary_calibration_private_ledgers BEGIN SELECT RAISE(ABORT,'immutable calibration evidence'); END;
CREATE TRIGGER binary_calibration_private_ledgers_erase BEFORE DELETE ON binary_calibration_private_ledgers WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_private_ledgers_stage BEFORE INSERT ON binary_calibration_private_ledgers BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TABLE binary_calibration_artifacts (
 id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 private_ledger_id TEXT NOT NULL,
 artifact_revision INTEGER NOT NULL,
 predecessor_artifact_id TEXT,
 correction_reason TEXT,
 status TEXT NOT NULL,
 contract TEXT NOT NULL,
 canonical_bytes BLOB NOT NULL,
 artifact_digest TEXT NOT NULL,
 evidence_digest TEXT NOT NULL,
 created_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(run_id),
 UNIQUE(private_ledger_id),
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,private_ledger_id) REFERENCES binary_calibration_private_ledgers(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,predecessor_artifact_id) REFERENCES binary_calibration_artifacts(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK(length(artifact_digest)=71 AND substr(artifact_digest,1,7)='sha256:' AND substr(artifact_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK(length(evidence_digest)=71 AND substr(evidence_digest,1,7)='sha256:' AND substr(evidence_digest,8) NOT GLOB '*[^0-9a-f]*'),
 CHECK ((artifact_revision > 0)),
 CHECK (((length(canonical_bytes) >= 2) AND (length(canonical_bytes) <= 16777216))),
 CHECK ((((artifact_revision = 1) AND (predecessor_artifact_id IS NULL) AND (correction_reason IS NULL)) OR ((artifact_revision > 1) AND (predecessor_artifact_id IS NOT NULL) AND (correction_reason IS NOT NULL)))),
 CHECK ((contract = 'rubrist/binary-calibration/v1')),
 CHECK ((status IN ('complete', 'incomplete')))
) STRICT;
CREATE TRIGGER binary_calibration_artifacts_immutable BEFORE UPDATE ON binary_calibration_artifacts BEGIN SELECT RAISE(ABORT,'immutable calibration evidence'); END;
CREATE TRIGGER binary_calibration_artifacts_erase BEFORE DELETE ON binary_calibration_artifacts WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_artifacts_stage BEFORE INSERT ON binary_calibration_artifacts BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TABLE binary_calibration_revision_leases (
 dataset_revision_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 lease_generation INTEGER NOT NULL DEFAULT 1,
 acquired_at TEXT NOT NULL,
 PRIMARY KEY(dataset_revision_id),
 UNIQUE(project_id,dataset_revision_id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 UNIQUE(run_id),
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,dataset_revision_id) REFERENCES dataset_revisions(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK ((lease_generation > 0))
) STRICT;
CREATE TRIGGER binary_calibration_revision_leases_erase BEFORE DELETE ON binary_calibration_revision_leases WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_revision_leases_stage BEFORE INSERT ON binary_calibration_revision_leases BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TABLE binary_calibration_revocation_events (
 id TEXT NOT NULL,
 artifact_id TEXT NOT NULL,
 run_id TEXT NOT NULL,
 project_id TEXT NOT NULL,
 reason TEXT NOT NULL,
 evidence_ref_kind TEXT NOT NULL,
 evidence_ref_id TEXT NOT NULL,
 occurred_at TEXT NOT NULL,
 PRIMARY KEY(id),
 UNIQUE(project_id,id),
 FOREIGN KEY(project_id) REFERENCES projects(id) ON DELETE CASCADE,
 FOREIGN KEY(project_id,run_id) REFERENCES binary_calibration_runs(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,artifact_id) REFERENCES binary_calibration_artifacts(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 CHECK (((length(evidence_ref_id) > 0) AND (length(CAST(evidence_ref_id AS BLOB)) <= 4096))),
 CHECK (((length(evidence_ref_kind) > 0) AND (length(CAST(evidence_ref_kind AS BLOB)) <= 256))),
 CHECK ((reason IN ('development_exposure', 'provider_policy_invalidated', 'provenance_invalidated', 'artifact_superseded')))
) STRICT;
CREATE TRIGGER binary_calibration_revocation_events_immutable BEFORE UPDATE ON binary_calibration_revocation_events BEGIN SELECT RAISE(ABORT,'immutable calibration evidence'); END;
CREATE TRIGGER binary_calibration_revocation_events_erase BEFORE DELETE ON binary_calibration_revocation_events WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'calibration deletion requires project erasure'); END;
CREATE TRIGGER binary_calibration_revocation_events_stage BEFORE INSERT ON binary_calibration_revocation_events BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE TRIGGER binary_calibration_run_insert BEFORE INSERT ON binary_calibration_runs BEGIN
 SELECT CASE WHEN NEW.created_at IS NOT sqlite_command_time() OR NEW.state<>'queued' OR NEW.accounted_observations<>0 OR NEW.planned_observations<>NEW.item_count OR NEW.claim_token IS NOT NULL OR NEW.authorization_check_id IS NOT NULL OR NEW.completion_check_id IS NOT NULL OR NEW.artifact_id IS NOT NULL OR NEW.artifact_digest IS NOT NULL OR NEW.evidence_digest IS NOT NULL OR NEW.rejection_reason IS NOT NULL OR NEW.started_at IS NOT NULL OR NEW.completed_at IS NOT NULL THEN RAISE(ABORT,'calibration creation requires fresh queued command') END;
 SELECT CASE WHEN NEW.provider_policy_digest IS NOT governed_bytes_v1_digest(NEW.provider_policy_canonical_bytes) THEN RAISE(ABORT,'calibration provider policy byte digest mismatch') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM dataset_revisions r JOIN skill_versions v ON v.id=NEW.skill_version_id AND v.project_id=r.project_id JOIN skills s ON s.id=v.skill_id AND s.project_id=v.project_id JOIN criterion_versions cv ON cv.id=v.criterion_version_id AND cv.project_id=v.project_id
 WHERE r.id=NEW.dataset_revision_id AND r.project_id=NEW.project_id AND r.role='sealed_validation' AND r.source_kind='sealed_intake' AND r.provenance_level='governed_blind' AND r.revision_digest=NEW.revision_digest AND r.content_digest=NEW.truth_content_digest AND r.item_count=NEW.item_count
 AND v.skill_id=NEW.skill_id AND v.criterion_version_id=NEW.criterion_version_id AND governed_canonical_json_v1(v.execution_binding)=governed_canonical_json_v1(NEW.execution_binding) AND s.criterion_id=NEW.criterion_id AND cv.criterion_id=NEW.criterion_id AND cv.criterion_digest=NEW.criterion_digest)
 THEN RAISE(ABORT,'calibration requires exact governed sealed evaluator lineage') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM governed_review_batches b JOIN review_instruction_versions i ON i.id=b.instruction_version_id JOIN governed_review_batch_events f ON f.batch_id=b.id AND f.event_kind='frozen' WHERE b.id=NEW.governed_review_batch_id AND b.project_id=NEW.project_id AND b.criterion_version_id=NEW.criterion_version_id AND b.content_digest=NEW.governed_review_batch_digest AND b.instruction_version_id=NEW.review_instruction_version_id AND i.content_digest=NEW.review_instruction_digest AND f.dataset_revision_id=NEW.dataset_revision_id AND b.population_id=NEW.population_id AND b.population_digest=NEW.population_digest AND b.draw_digest=NEW.draw_digest AND b.selection_method=NEW.selection_method) THEN RAISE(ABORT,'calibration requires exact frozen batch origin') END;
 SELECT CASE WHEN NEW.suite_manifest_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM evaluator_suite_manifests m JOIN json_each(CAST(m.canonical_bytes AS TEXT),'$.members') x ON x.key=NEW.suite_member_position WHERE m.id=NEW.suite_manifest_id AND m.project_id=NEW.project_id AND m.manifest_digest=NEW.suite_manifest_digest AND json_type(CAST(m.canonical_bytes AS TEXT),'$.trialPlan')='null' AND json_extract(x.value,'$.skillVersionId')=NEW.skill_version_id AND json_extract(x.value,'$.criterionVersionId')=NEW.criterion_version_id AND json_extract(x.value,'$.skillDigest')=NEW.skill_digest AND json_extract(x.value,'$.outputContractDigest')=NEW.output_contract_digest) THEN RAISE(ABORT,'calibration requires exact single-trial suite member') END;
END;
CREATE TRIGGER binary_calibration_run_stage BEFORE UPDATE ON binary_calibration_runs BEGIN SELECT RAISE(ABORT,'calibration execution requires complete owning commands'); END;
CREATE UNIQUE INDEX binary_calibration_one_active_revision_skill ON binary_calibration_runs(dataset_revision_id,skill_version_id) WHERE state IN('queued','running','recovery_required');
CREATE INDEX binary_calibration_runs_project_created ON binary_calibration_runs(project_id,created_at DESC,id DESC);
CREATE INDEX binary_calibration_runs_runnable ON binary_calibration_runs(state,claim_expires_at,created_at,id) WHERE state IN('queued','running','recovery_required');
CREATE INDEX binary_calibration_attempts_next ON binary_calibration_attempts(run_id,accounting_state,trial_index,dataset_revision_item_digest);
CREATE UNIQUE INDEX binary_calibration_artifact_digest ON binary_calibration_artifacts(artifact_digest);
CREATE UNIQUE INDEX binary_calibration_attempt_salt ON binary_calibration_attempts(commitment_salt);
CREATE UNIQUE INDEX binary_calibration_attempt_item_digest ON binary_calibration_attempts(run_id,dataset_revision_item_digest,trial_index);
CREATE UNIQUE INDEX binary_calibration_revocation_identity ON binary_calibration_revocation_events(artifact_id,reason,evidence_ref_kind,evidence_ref_id);
