-- Every activation bundle must satisfy reciprocal retirement before commit.
CREATE TABLE evaluator_activation_claims (
 event_id TEXT PRIMARY KEY NOT NULL,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
 bundle_id TEXT NOT NULL,command_token TEXT NOT NULL,
 FOREIGN KEY(project_id,event_id) REFERENCES evaluator_lifecycle_events(project_id,id) DEFERRABLE INITIALLY DEFERRED,
 FOREIGN KEY(project_id,bundle_id,command_token) REFERENCES evaluator_activation_finalizations(project_id,bundle_id,command_token) DEFERRABLE INITIALLY DEFERRED
) STRICT;
CREATE TABLE evaluator_activation_finalizations (
 bundle_id TEXT PRIMARY KEY NOT NULL,project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,command_token TEXT NOT NULL,
 UNIQUE(project_id,bundle_id,command_token)
) STRICT;
CREATE TRIGGER evaluator_activation_claims_immutable BEFORE UPDATE ON evaluator_activation_claims BEGIN SELECT RAISE(ABORT,'immutable activation bundle'); END;
CREATE TRIGGER evaluator_activation_claims_erase BEFORE DELETE ON evaluator_activation_claims WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'activation deletion requires project erasure'); END;
CREATE TRIGGER evaluator_activation_finalizations_immutable BEFORE UPDATE ON evaluator_activation_finalizations BEGIN SELECT RAISE(ABORT,'immutable activation bundle'); END;
CREATE TRIGGER evaluator_activation_finalizations_erase BEFORE DELETE ON evaluator_activation_finalizations WHEN EXISTS(SELECT 1 FROM projects WHERE id=OLD.project_id) BEGIN SELECT RAISE(ABORT,'activation deletion requires project erasure'); END;
CREATE TRIGGER evaluator_activation_claim_insert BEFORE INSERT ON evaluator_activation_claims BEGIN
 SELECT CASE WHEN NEW.command_token IS NOT sqlite_command_token() OR EXISTS(SELECT 1 FROM evaluator_activation_finalizations WHERE bundle_id=NEW.bundle_id) OR NOT EXISTS(SELECT 1 FROM evaluator_lifecycle_events WHERE project_id=NEW.project_id AND id=NEW.event_id AND activation_bundle_id=NEW.bundle_id AND occurred_at=sqlite_command_time()) THEN RAISE(ABORT,'activation claim requires owning event command') END;
END;
CREATE TRIGGER evaluator_lifecycle_activation_claim AFTER INSERT ON evaluator_lifecycle_events WHEN NEW.activation_bundle_id IS NOT NULL BEGIN
 INSERT INTO evaluator_activation_claims(event_id,project_id,bundle_id,command_token) VALUES(NEW.id,NEW.project_id,NEW.activation_bundle_id,sqlite_command_token());
END;
CREATE TRIGGER evaluator_lifecycle_activation_finalize BEFORE INSERT ON evaluator_activation_finalizations BEGIN
 SELECT CASE WHEN NEW.command_token IS NOT sqlite_command_token() OR NOT EXISTS(SELECT 1 FROM evaluator_activation_claims WHERE project_id=NEW.project_id AND bundle_id=NEW.bundle_id AND command_token=NEW.command_token) OR EXISTS(SELECT 1 FROM evaluator_activation_claims WHERE bundle_id=NEW.bundle_id AND (project_id<>NEW.project_id OR command_token<>NEW.command_token)) OR analysis_lifecycle_activation_bundle_valid_v1(NEW.project_id,NEW.bundle_id)=0 THEN RAISE(ABORT,'activation bundle requires exact reciprocal replacement') END;
END;
DROP TRIGGER evaluator_lifecycle_seed_insert;
CREATE TRIGGER evaluator_lifecycle_seed_insert BEFORE INSERT ON evaluator_lifecycle_events WHEN NEW.sequence IS NULL OR NEW.sequence=1 BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM evaluator_candidate_open_claims WHERE lifecycle_id=NEW.lifecycle_id AND project_id=NEW.project_id AND skill_version_id=NEW.skill_version_id) THEN RAISE(ABORT,'seed requires owning unfinalized candidate claim') END;
END;
CREATE TRIGGER evaluator_lifecycle_transition_insert BEFORE INSERT ON evaluator_lifecycle_events WHEN NEW.sequence<>1 BEGIN
 SELECT CASE WHEN NEW.occurred_at IS NOT sqlite_command_time() OR NOT EXISTS(SELECT 1 FROM evaluator_candidate_claims q JOIN evaluator_lifecycle_finalizations f ON f.lifecycle_id=q.lifecycle_id WHERE q.lifecycle_id=NEW.lifecycle_id AND q.project_id=NEW.project_id AND q.command_token<>sqlite_command_token()) THEN RAISE(ABORT,'transition requires previously committed candidate') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM evaluator_activation_finalizations WHERE bundle_id=NEW.activation_bundle_id) OR EXISTS(SELECT 1 FROM evaluator_activation_claims q JOIN evaluator_activation_finalizations f ON f.bundle_id=q.bundle_id JOIN evaluator_lifecycle_events e ON e.id=q.event_id WHERE e.lifecycle_id=NEW.lifecycle_id AND f.command_token=sqlite_command_token()) THEN RAISE(ABORT,'finalized activation cannot change in its command') END;
 SELECT CASE WHEN analysis_lifecycle_transition_valid_v1(json_object('id',NEW.id,'contract_version',NEW.contract_version,'lifecycle_id',NEW.lifecycle_id,'project_id',NEW.project_id,'criterion_id',NEW.criterion_id,'skill_version_id',NEW.skill_version_id,'sequence',CAST(NEW.sequence AS TEXT),'transition',NEW.transition,'state',NEW.state,'predecessor_event_id',NEW.predecessor_event_id,'predecessor_event_digest',NEW.predecessor_event_digest,'activation_bundle_id',NEW.activation_bundle_id,'calibration_artifact_id',NEW.calibration_artifact_id,'calibration_artifact_digest',NEW.calibration_artifact_digest,'calibration_evidence_digest',NEW.calibration_evidence_digest,'regression_run_id',NEW.regression_run_id,'regression_dataset_revision_id',NEW.regression_dataset_revision_id,'replaced_skill_version_id',NEW.replaced_skill_version_id,'actor_user_id',NEW.actor_user_id,'actor_subject_id',NEW.actor_subject_id,'actor_role',NEW.actor_role,'reason',NEW.reason,'idempotency_key',NEW.idempotency_key,'request_digest',NEW.request_digest,'content_digest',NEW.content_digest,'occurred_at',NEW.occurred_at))=0 THEN RAISE(ABORT,'lifecycle transition evidence or head mismatch') END;
END;
CREATE TRIGGER binary_calibration_revocation_lifecycle AFTER INSERT ON binary_calibration_revocation_events BEGIN
 INSERT INTO evaluator_lifecycle_events(id,contract_version,lifecycle_id,project_id,criterion_id,skill_version_id,sequence,transition,state,predecessor_event_id,predecessor_event_digest,activation_bundle_id,calibration_artifact_id,calibration_artifact_digest,calibration_evidence_digest,regression_run_id,regression_dataset_revision_id,replaced_skill_version_id,actor_user_id,actor_subject_id,actor_role,reason,idempotency_key,request_digest,content_digest,occurred_at) SELECT 'elce_'||substr(replace(governed_content_v1_digest('evaluator-lifecycle-revocation-id/v1',json_object('revocationId',NEW.id)),':',''),8,48),'rubrist/evaluator-lifecycle-event/v1',h.lifecycle_id,h.project_id,h.criterion_id,h.skill_version_id,CAST(h.sequence+1 AS TEXT),'calibration_revoked','needs_review',h.id,h.content_digest,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'system','Calibration artifact revoked: '||NEW.reason,'calibration-revocation:'||NEW.id,governed_content_v1_digest('evaluator-lifecycle-revocation-request/v1',json_object('artifactId',NEW.artifact_id,'lifecycleId',h.lifecycle_id,'revocationId',NEW.id)),sqlite_lifecycle_event_digest(json_object('id','elce_'||substr(replace(governed_content_v1_digest('evaluator-lifecycle-revocation-id/v1',json_object('revocationId',NEW.id)),':',''),8,48),'contract_version','rubrist/evaluator-lifecycle-event/v1','lifecycle_id',h.lifecycle_id,'project_id',h.project_id,'criterion_id',h.criterion_id,'skill_version_id',h.skill_version_id,'sequence',CAST(h.sequence+1 AS TEXT),'transition','calibration_revoked','state','needs_review','predecessor_event_id',h.id,'predecessor_event_digest',h.content_digest,'activation_bundle_id',NULL,'calibration_artifact_id',NULL,'calibration_artifact_digest',NULL,'calibration_evidence_digest',NULL,'regression_run_id',NULL,'regression_dataset_revision_id',NULL,'replaced_skill_version_id',NULL,'actor_user_id',NULL,'actor_subject_id',NULL,'actor_role','system','reason','Calibration artifact revoked: '||NEW.reason,'idempotency_key','calibration-revocation:'||NEW.id,'request_digest',governed_content_v1_digest('evaluator-lifecycle-revocation-request/v1',json_object('artifactId',NEW.artifact_id,'lifecycleId',h.lifecycle_id,'revocationId',NEW.id)),'content_digest','sha256:'||printf('%064d',0),'occurred_at',sqlite_command_time())),sqlite_command_time() FROM evaluator_lifecycle_heads h WHERE h.project_id=NEW.project_id AND h.state='active' AND h.transition='activated' AND h.calibration_artifact_id=NEW.artifact_id AND NOT EXISTS(SELECT 1 FROM evaluator_lifecycle_events WHERE project_id=NEW.project_id AND idempotency_key='calibration-revocation:'||NEW.id);
 SELECT CASE WHEN EXISTS(SELECT 1 FROM evaluator_lifecycle_heads WHERE project_id=NEW.project_id AND state='active' AND calibration_artifact_id=NEW.artifact_id) THEN RAISE(ABORT,'revocation must append needs-review lifecycle event') END;
END;
-- PostgreSQL also rejects a no-op UPDATE once activation cites this row.
CREATE TRIGGER regression_run_activated_immutable BEFORE UPDATE ON regression_runs
WHEN EXISTS(SELECT 1 FROM evaluator_lifecycle_events WHERE regression_run_id=OLD.id AND transition='activated')
BEGIN SELECT RAISE(ABORT,'regression evidence cited by evaluator activation is immutable'); END;
