-- Preserve PG label-set semantics without imposing JSON text formatting/order.
DROP TRIGGER governed_truth_insert;
CREATE TRIGGER governed_truth_insert BEFORE INSERT ON governed_dataset_truth_links BEGIN
 SELECT CASE WHEN NEW.created_at IS NOT sqlite_command_time() OR NEW.created_command_token IS NOT sqlite_command_token() OR EXISTS(SELECT 1 FROM dataset_revision_finalizations WHERE revision_id=NEW.dataset_revision_id) THEN RAISE(ABORT,'truth link requires current unfinalized revision command') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM dataset_revisions r JOIN dataset_revision_items i ON i.revision_id=r.id AND i.project_id=r.project_id WHERE r.id=NEW.dataset_revision_id AND r.project_id=NEW.project_id AND i.id=NEW.dataset_revision_item_id AND r.criterion_version_id=NEW.criterion_version_id AND i.reference_label=NEW.resolved_label AND json_extract(i.reference_provenance,'$.kind')='dataset_claim' AND json_extract(i.reference_provenance,'$.sourceId')=NEW.id) THEN RAISE(ABORT,'truth link requires exact revision item criterion label and compatibility pointer') END;
 SELECT CASE WHEN json_array_length(NEW.governed_label_ids)>20 OR EXISTS(SELECT 1 FROM json_each(NEW.governed_label_ids) WHERE type<>'text' OR length(value)=0 OR length(CAST(value AS BLOB))>256) OR (SELECT coalesce(sum(length(CAST(value AS BLOB))),0) FROM json_each(NEW.governed_label_ids))>4096 THEN RAISE(ABORT,'invalid truth label ids') END;
 SELECT CASE WHEN NEW.source_kind IN('governed_labels','adjudication') AND NOT EXISTS(SELECT 1 FROM governed_review_batch_items bi JOIN governed_review_batches b ON b.id=bi.batch_id JOIN governed_review_batch_states bs ON bs.batch_id=b.id JOIN governed_review_items ri ON ri.id=bi.review_item_id JOIN governed_review_item_resolutions res ON res.batch_item_id=bi.id JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id JOIN dataset_revision_items i ON i.id=NEW.dataset_revision_item_id WHERE bi.id=NEW.batch_item_id AND b.project_id=NEW.project_id AND b.criterion_version_id=NEW.criterion_version_id AND bs.state='resolved' AND r.role=b.role_intent AND (b.role_intent<>'sealed_validation' OR (ri.source_kind='sealed_intake' AND r.source_kind='sealed_intake' AND r.parent_revision_id IS ri.sealed_predecessor_revision_id)) AND r.provenance_level='governed_blind' AND i.input_digest=ri.input_digest AND governed_canonical_json_v1(i.payload_snapshot)=governed_canonical_json_v1(ri.review_payload_snapshot) AND res.resolution_kind=NEW.resolution_kind AND res.resolved_label=NEW.resolved_label AND res.adjudication_id IS NEW.adjudication_id) THEN RAISE(ABORT,'native truth requires exact resolved batch evidence') END;
 SELECT CASE WHEN NEW.source_kind='governed_labels' AND (NEW.supporting_label_count<>json_array_length(NEW.governed_label_ids) OR NEW.supporting_label_count<>(SELECT required_labels_per_item FROM governed_review_batches b JOIN governed_review_batch_items i ON i.batch_id=b.id WHERE i.id=NEW.batch_item_id) OR (SELECT count(DISTINCT value) FROM json_each(NEW.governed_label_ids))<>NEW.supporting_label_count OR EXISTS(SELECT 1 FROM json_each(NEW.governed_label_ids) named WHERE NOT EXISTS(SELECT 1 FROM governed_active_review_labels active WHERE active.batch_item_id=NEW.batch_item_id AND active.label_id=named.value)) OR (SELECT count(*) FROM governed_active_review_labels WHERE batch_item_id=NEW.batch_item_id)<>NEW.supporting_label_count) THEN RAISE(ABORT,'truth must name every exact active independent label') END;
 SELECT CASE WHEN NEW.source_kind='adjudication' AND NOT EXISTS(SELECT 1 FROM governed_review_adjudications a WHERE a.id=NEW.adjudication_id AND a.batch_item_id=NEW.batch_item_id AND a.decision=NEW.resolved_label AND a.considered_label_count=NEW.supporting_label_count) THEN RAISE(ABORT,'truth requires exact authoritative adjudication') END;
 SELECT CASE WHEN NEW.source_kind='imported_truth' AND NOT EXISTS(SELECT 1 FROM governed_imported_truth t JOIN dataset_revisions r ON r.id=NEW.dataset_revision_id JOIN dataset_revision_items i ON i.id=NEW.dataset_revision_item_id WHERE t.id=NEW.imported_truth_id AND r.role IN('analysis_authoring','iterative_development') AND r.source_kind='collection_snapshot' AND t.project_id=NEW.project_id AND t.criterion_version_id=NEW.criterion_version_id AND t.input_digest=i.input_digest AND governed_canonical_json_v1(t.payload_snapshot)=governed_canonical_json_v1(i.payload_snapshot) AND t.label=NEW.resolved_label AND NEW.resolution_kind=CASE t.evidence_class WHEN 'imported_self_attested' THEN 'imported_self_attested' WHEN 'imported_verified_attested' THEN 'imported_verified_attested' ELSE 'imported_unverified' END AND r.provenance_level=CASE t.evidence_class WHEN 'imported_self_attested' THEN 'imported_self_attested' WHEN 'imported_verified_attested' THEN 'imported_verified_attested' ELSE 'unverified' END) THEN RAISE(ABORT,'imported truth must preserve exact artifact and honest provenance') END;
 SELECT CASE WHEN NEW.content_digest IS NOT governed_content_v1_digest('governed-dataset-truth-link/v1',json_object('adjudicationId',NEW.adjudication_id,'batchItemId',NEW.batch_item_id,'criterionVersionId',NEW.criterion_version_id,'datasetRevisionId',NEW.dataset_revision_id,'datasetRevisionItemId',NEW.dataset_revision_item_id,'governedLabelIds',json(NEW.governed_label_ids),'importedTruthId',NEW.imported_truth_id,'resolutionKind',NEW.resolution_kind,'resolvedLabel',NEW.resolved_label,'sourceKind',NEW.source_kind,'supportingLabelCount',NEW.supporting_label_count)) THEN RAISE(ABORT,'truth content digest mismatch') END;
END;

DROP TRIGGER subject_identity_immutable;
CREATE TRIGGER subject_identity_immutable BEFORE UPDATE ON governed_reviewer_subjects WHEN NOT(
 OLD.account_user_id IS NOT NULL AND NEW.account_user_id IS NULL
 AND NOT EXISTS(SELECT 1 FROM "user" WHERE id=OLD.account_user_id)
 AND NEW.id IS OLD.id AND NEW.project_id IS OLD.project_id
 AND NEW.subject_digest IS OLD.subject_digest AND NEW.created_at IS OLD.created_at)
BEGIN SELECT RAISE(ABORT,'immutable reviewer subject'); END;
