import type {DatabaseSync,SQLInputValue} from 'node:sqlite';
import type {BinaryCalibrationActor,CreateBinaryCalibrationRunInput} from '../../binary-calibration/repository.js';
import {BinaryCalibrationRepositoryError} from '../../binary-calibration/repository.js';
import {requireOwner,validateCreateInput,repoError,stableId,rowToRun,type RunRow} from '../../binary-calibration/storage-values.js';
import {sha256Digest} from '../../lib/canonical-json.js';
import {sqliteCommand} from './command-context.js';
import {deriveRunIdentity} from './calibration-identity.js';
/** Internal run control. Execution stays staged until all lease and mint commands land. */
export function createCalibrationRun(db:DatabaseSync,actor:BinaryCalibrationActor,input:CreateBinaryCalibrationRunInput,clock=Date.now){
 requireOwner(actor);validateCreateInput(input);
 try{return sqliteCommand(db,c=>{
  if(!c.db.prepare("SELECT 1 FROM project_members WHERE project_id=? AND user_id=? AND role='owner'").get(actor.projectId,actor.userId))throw repoError('forbidden','only a project owner may start sealed calibration');
  const derived=deriveRunIdentity(db,actor.projectId,input);
  const requestDigest=sha256Digest({datasetRevisionId:input.datasetRevisionId,idempotencyKey:input.idempotencyKey,positiveClass:input.positiveClass,providerDataHandling:derived.providerPolicy,skillVersionId:input.skillVersionId,suiteBinding:input.suiteBinding,trialPlan:input.trialPlan});
  const existing=c.db.prepare('SELECT * FROM binary_calibration_runs WHERE project_id=? AND idempotency_key=?').get(actor.projectId,input.idempotencyKey);
  if(existing){if(existing.request_digest!==requestDigest)throw repoError('idempotency_conflict','binary calibration idempotency key was reused with different input');return rowToRun(existing as unknown as RunRow);}
  const row:Record<string,SQLInputValue>={id:stableId('bcr',actor.projectId,input.idempotencyKey),project_id:actor.projectId,dataset_revision_id:input.datasetRevisionId,revision_digest:derived.revisionDigest,truth_content_digest:derived.truthContentDigest,item_count:derived.itemCount,criterion_id:derived.criterionId,criterion_version_id:derived.criterionVersionId,criterion_digest:derived.criterionDigest,skill_id:derived.skillVersion.skillId,skill_version_id:derived.skillVersion.id,skill_digest:derived.skillDigest,output_contract_digest:derived.outputContractDigest,requested_provider:derived.executionBinding.provider,definition_digest:derived.definitionDigest,execution_binding:JSON.stringify(derived.executionBinding),requested_binding_digest:derived.requestedBindingDigest,suite_manifest_id:derived.suiteBinding?.manifestId??null,suite_manifest_digest:derived.suiteBinding?.manifestDigest??null,suite_member_position:derived.suiteBinding?.memberPosition??null,governed_review_batch_id:derived.origin.batchId,governed_review_batch_digest:derived.origin.batchDigest,review_instruction_version_id:derived.origin.instructionVersionId,review_instruction_digest:derived.origin.instructionDigest,population_id:derived.origin.populationId,population_digest:derived.origin.populationDigest,draw_digest:derived.origin.drawDigest,representative_of_population_id:derived.representativeness.representativeOfPopulationId,representative_ineligible_reasons:JSON.stringify(derived.representativeness.reasons),selection_method:derived.origin.selectionMethod,positive_class:input.positiveClass,trial_plan_kind:'single',trials_per_item:1,execution_environment:derived.providerPolicy.executionEnvironment,provider_policy_id:derived.providerPolicy.policyId,provider_policy_digest:derived.providerPolicy.policyDigest,provider_policy_canonical_bytes:derived.providerPolicyBytes,payload_transmission:derived.providerPolicy.payloadTransmission,idempotency_key:input.idempotencyKey,request_digest:requestDigest,state:'queued',planned_observations:derived.itemCount,created_at:c.timestamp};
  c.db.prepare(`INSERT INTO binary_calibration_runs(${Object.keys(row).join(',')}) VALUES(${Object.keys(row).map(()=>'?')})`).run(...Object.values(row));
  return rowToRun(c.db.prepare('SELECT * FROM binary_calibration_runs WHERE id=?').get(row.id!) as unknown as RunRow);
 },clock);}catch(error){if(error instanceof BinaryCalibrationRepositoryError)throw error;const e=error as {errcode?:number;message?:string};if(((e.errcode??0)&255)===19)throw repoError(e.message?.includes('binary_calibration_runs.project_id, binary_calibration_runs.idempotency_key')?'idempotency_conflict':e.message?.includes('UNIQUE')?'state_conflict':'ineligible','binary calibration identity or invariant is ineligible');throw error;}
}
