import type { DatabaseSync } from 'node:sqlite';
import type { GovernedReviewActor,GovernedReviewRepository } from '../../governed-review/repository.js';
import type { GovernedReviewBatchProjection,GovernedReviewerTaskProjection,GovernedPostBarrierItemProjection } from '../../governed-review/contracts.js';
import { GovernedReviewForbiddenError,GovernedReviewNotFoundError } from '../../governed-review/errors.js';
import { assertBlindProjectionSafe } from '../../governed-review/projection.js';
import { governedReviewAccess,governedReviewSubject } from './governed-subject-commands.js';
import { governedEvidenceCommand,checkGovernedSeparation } from './governed-capability-commands.js';
import { sqliteCommand,type SqliteCommandDatabase } from './command-context.js';
const iso=(v:unknown)=>new Date(String(v)).toISOString();
export function governedBatchProjection(db:SqliteCommandDatabase,projectId:string,batchId:string):GovernedReviewBatchProjection {
 const row=db.prepare(`SELECT b.*,s.state,s.state_version,e.dataset_revision_id,e.representative_of_population_id,e.representative_ineligible_reasons FROM governed_review_batches b JOIN governed_review_batch_states s ON s.batch_id=b.id LEFT JOIN governed_review_batch_events e ON e.batch_id=b.id AND e.event_kind='frozen' WHERE b.id=? AND b.project_id=?`).get(batchId,projectId);if(!row)throw new GovernedReviewNotFoundError();
 const barrier=!['draft','open'].includes(String(row.state)),resolution=barrier&&row.role_intent!=='sealed_validation',frozen=row.state==='frozen',population=row.representative_of_population_id===null?null:String(row.representative_of_population_id);
 const items=db.prepare('SELECT i.id,i.serve_position,r.resolution_kind,r.resolved_label FROM governed_review_batch_items i JOIN governed_review_item_resolutions r ON r.batch_item_id=i.id WHERE i.batch_id=? ORDER BY i.serve_position,i.id').all(batchId);
 const counts=db.prepare("SELECT count(*) total,coalesce(sum(state='submitted'),0) submitted,coalesce(sum(state='deferred'),0) deferred,coalesce(sum(state='expired'),0) expired,coalesce(sum(state IN('assigned','viewed','withdrawn')),0) pending FROM governed_review_task_states WHERE batch_id=?").get(batchId)!;
 return {batchId,criterionVersionId:String(row.criterion_version_id),instructionVersionId:String(row.instruction_version_id),roleIntent:row.role_intent as GovernedReviewBatchProjection['roleIntent'],sourcePopulationKind:row.source_population_kind as GovernedReviewBatchProjection['sourcePopulationKind'],sourcePopulationId:String(row.source_population_id),evaluatorBlind:Boolean(row.evaluator_blind),peerBlindUntilLabelingClosed:Boolean(row.peer_blind_until_labeling_closed),selectionMethod:row.selection_method as GovernedReviewBatchProjection['selectionMethod'],batchDigest:String(row.content_digest),populationDigest:String(row.population_digest),drawDigest:String(row.draw_digest),fixedBudget:Number(row.fixed_budget),requiredIndependentLabels:Number(row.required_labels_per_item),state:row.state as GovernedReviewBatchProjection['state'],stateVersion:Number(row.state_version),fixedStopAt:iso(row.stop_at),itemCount:Number(row.fixed_budget),items:items.map(i=>({batchItemId:String(i.id),servePosition:Number(i.serve_position),resolutionKind:resolution?i.resolution_kind as GovernedReviewBatchProjection['items'][number]['resolutionKind']:null,resolvedLabel:resolution?i.resolved_label as 'pass'|'fail'|null:null})),completeness:barrier?{totalTasks:Number(counts.total),submittedTasks:Number(counts.submitted),deferredTasks:Number(counts.deferred),expiredTasks:Number(counts.expired),pendingTasks:Number(counts.pending)}:null,representativeness:frozen?{status:population?'eligible':'ineligible',populationId:population,reasons:population?[]:JSON.parse(String(row.representative_ineligible_reasons))}:{status:'not_evaluated',populationId:null,reasons:[]},datasetRevisionId:row.dataset_revision_id===null?null:String(row.dataset_revision_id),evidenceClass:frozen?'governed_blind':null,createdAt:iso(row.created_at)};
}
export function sqliteGovernedReadCommands(db:DatabaseSync,clock=Date.now){return {
 governedBatchSummary(...[actor,batchId]:Parameters<GovernedReviewRepository['getBatchSummary']>){return sqliteCommand(db,c=>{governedReviewAccess(db,actor);return governedBatchProjection(c.db,actor.projectId,batchId);},clock);},
 governedBatchList(...[actor,query]:Parameters<GovernedReviewRepository['listBatches']>){return sqliteCommand(db,c=>{governedReviewAccess(db,actor);return c.db.prepare('SELECT b.id FROM governed_review_batches b JOIN governed_review_batch_states s ON s.batch_id=b.id WHERE b.project_id=? AND (? IS NULL OR b.criterion_version_id=?) AND (? IS NULL OR s.state=?) ORDER BY b.created_at DESC,b.id').all(actor.projectId,query.criterionVersionId??null,query.criterionVersionId??null,query.state??null,query.state??null).map(r=>governedBatchProjection(c.db,actor.projectId,String(r.id)));},clock);},
 governedReviewerTasks(actor:GovernedReviewActor):GovernedReviewerTaskProjection[]{return sqliteCommand(db,c=>{
  governedReviewAccess(db,actor);
  return c.db.prepare(`SELECT t.id task_id,t.batch_id,b.criterion_version_id,b.instruction_version_id,cv.name criterion_name,i.title instruction_title,s.state,s.state_version,t.serve_order,b.stop_at,a.label_id FROM governed_review_tasks t JOIN governed_reviewer_subjects subject ON subject.id=t.reviewer_subject_id JOIN governed_review_batches b ON b.id=t.batch_id JOIN governed_review_batch_states bs ON bs.batch_id=b.id JOIN governed_review_task_states s ON s.task_id=t.id JOIN criterion_versions cv ON cv.id=b.criterion_version_id JOIN review_instruction_versions i ON i.id=b.instruction_version_id LEFT JOIN governed_active_review_labels a ON a.task_id=t.id WHERE t.project_id=? AND subject.account_user_id=? AND bs.state NOT IN('draft','abandoned') ORDER BY b.created_at DESC,t.serve_order,t.id`).all(actor.projectId,actor.userId).map(r=>({taskId:String(r.task_id),batchId:String(r.batch_id),criterionVersionId:String(r.criterion_version_id),instructionVersionId:String(r.instruction_version_id),criterionName:String(r.criterion_name),instructionTitle:String(r.instruction_title),state:r.state as GovernedReviewerTaskProjection['state'],stateVersion:Number(r.state_version),servePosition:Number(r.serve_order),fixedStopAt:iso(r.stop_at),activeLabelId:r.label_id===null?null:String(r.label_id)}));
 },clock);},
 governedPostBarrierView(...[actor,batchId,itemId,_purpose]:Parameters<GovernedReviewRepository['getPostBarrierItemView']>):GovernedPostBarrierItemProjection{return governedEvidenceCommand(db,c=>{
  governedReviewAccess(db,actor);const batch=c.db.prepare('SELECT state FROM governed_review_batch_states WHERE batch_id=? AND project_id=?').get(batchId,actor.projectId);if(!batch)throw new GovernedReviewNotFoundError();
  if(!['labeling_closed','alignment_open','adjudicating','resolved','incomplete','frozen'].includes(String(batch.state)))throw new GovernedReviewForbiddenError('Independent labels remain hidden until labeling closes');
  const subjectId=governedReviewSubject(db,actor.projectId,actor.userId,c.timestamp);
  if(!c.db.prepare('SELECT 1 FROM governed_review_tasks WHERE batch_id=? AND reviewer_subject_id=? LIMIT 1').get(batchId,subjectId))governedReviewAccess(db,actor,true);
  const item=c.db.prepare('SELECT id FROM governed_review_batch_items WHERE batch_id=? AND project_id=? AND (id=? OR review_item_id=?)').get(batchId,actor.projectId,itemId,itemId);if(!item)throw new GovernedReviewNotFoundError();
  const failed=checkGovernedSeparation(db,c,batchId,'adjudication',[subjectId],`post-barrier:${batchId}:${subjectId}`);if(failed)return failed;
  const row=c.db.prepare(`SELECT bi.id batch_item_id,b.criterion_version_id,cv.name criterion_name,cv.definition criterion_definition,iv.id instruction_version_id,iv.title,iv.instructions,iv.failure_code_guidance,ri.review_payload_snapshot,r.resolution_kind,r.resolved_label,r.adjudication_id,(SELECT coalesce(max(sequence),0) FROM governed_review_alignment_events WHERE batch_id=b.id) alignment_version FROM governed_review_batch_items bi JOIN governed_review_batches b ON b.id=bi.batch_id JOIN governed_review_items ri ON ri.id=bi.review_item_id JOIN criterion_versions cv ON cv.id=b.criterion_version_id JOIN review_instruction_versions iv ON iv.id=b.instruction_version_id JOIN governed_review_item_resolutions r ON r.batch_item_id=bi.id WHERE bi.id=?`).get(item.id!)!;
  const payload=JSON.parse(String(row.review_payload_snapshot));assertBlindProjectionSafe(payload);
  const labels=c.db.prepare('SELECT l.id,l.reviewer_subject_id,l.label,l.rationale,l.failure_codes FROM governed_active_review_labels a JOIN governed_review_labels l ON l.id=a.label_id WHERE a.batch_item_id=? ORDER BY l.id').all(item.id!);
  return {batchId,batchItemId:String(row.batch_item_id),alignmentVersion:Number(row.alignment_version),criterion:{criterionVersionId:String(row.criterion_version_id),name:String(row.criterion_name),definition:String(row.criterion_definition)},instruction:{instructionVersionId:String(row.instruction_version_id),title:String(row.title),instructions:String(row.instructions),failureCodeGuidance:String(row.failure_code_guidance)},payloadSnapshot:payload,activeLabels:labels.map(l=>({labelId:String(l.id),reviewerSubjectId:String(l.reviewer_subject_id),label:l.label as 'pass'|'fail'|'cannot_determine',rationale:String(l.rationale),failureCodes:JSON.parse(String(l.failure_codes))})),resolution:{kind:row.resolution_kind as GovernedPostBarrierItemProjection['resolution']['kind'],resolvedLabel:row.resolved_label as 'pass'|'fail'|null,adjudicationId:row.adjudication_id===null?null:String(row.adjudication_id)}};
 },clock);}
};}
