import { afterEach, expect, it, vi } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { openSqlite } from '@rubrist/db/sqlite';
import { CreateCriterionInputSchema } from '@rubrist/shared';
import { createUnseededSqliteRuntime } from './helpers/sqlite.js';
import { MOCK_BINDING, bindingInput } from './fixtures/execution-binding.js';
const cleanup:Array<()=>void|Promise<void>>=[];
afterEach(async()=>{for(const close of cleanup.splice(0).reverse())await close();vi.unstubAllEnvs();});
it('fences outbox ownership, preserves dispatch identity, and only deletes untouched submissions',async()=>{
 vi.stubEnv('BETTER_AUTH_SECRET','sqlite-dispatch-test-secret-at-least-32-characters');
 const dir=mkdtempSync(join(tmpdir(),'rubrist-dispatch-'));cleanup.push(()=>rmSync(dir,{recursive:true,force:true}));
 const path=join(dir,'db.sqlite'),runtime=await createUnseededSqliteRuntime(path);cleanup.push(()=>runtime.close());
 const {user}=await runtime.auth.api.signUpEmail({body:{email:'owner@example.test',password:'synthetic-long-password',name:'Owner'}});
 const {projectId}=await runtime.accounts.ensureWorkspaceForUser({userId:user.id,email:user.email,owner:true}),r=runtime.repository;
 const version=(await r.createCriterion(projectId,CreateCriterionInputSchema.parse({stableKey:'check',name:'Check',definition:'A check',evaluator:{rubricMarkdown:'Check',prompt:'Judge',executionBinding:bindingInput(MOCK_BINDING)}}),{})).evaluator.currentVersion.id;
 const trace=await r.importTrace(projectId,'manual',{input:'x',output:'y',metadata:{}},{ingestionPurpose:'judge_api'});
 const input={projectId,skillVersionId:version,trigger:'api_batch' as const,items:[{caseId:trace.caseId}]};
 const run=await r.createEvalRun(input),a={projectId,evalRunId:run.id,dispatchToken:'a'},b={...a,dispatchToken:'b'};
 const first=await r.claimEvalRunDispatch(a);expect(first.state).toBe('claimed');
 expect(await r.claimEvalRunDispatch(b)).toMatchObject({state:'busy',jobId:first.jobId});
 expect(await r.rotateEvalRunDispatchJob(b)).toBeNull();
 const rotated=await r.rotateEvalRunDispatchJob(a);expect(rotated).not.toBe(first.jobId);
 await r.releaseEvalRunDispatch(b);expect((await r.claimEvalRunDispatch(b)).state).toBe('busy');
 await r.releaseEvalRunDispatch(a);expect(await r.claimEvalRunDispatch(b)).toEqual({state:'claimed',jobId:rotated});
 const db=openSqlite(path);cleanup.push(()=>db.close());
 db.prepare('UPDATE eval_runs SET queue_dispatch_claimed_at=0 WHERE id=?').run(run.id);
 await r.markEvalRunDispatched(b);expect(db.prepare('SELECT queue_dispatched_at FROM eval_runs WHERE id=?').get(run.id)?.queue_dispatched_at).toBeNull();
 const c={...a,dispatchToken:'c'};expect((await r.claimEvalRunDispatch(c)).state).toBe('claimed');await r.markEvalRunDispatched(c);
 expect(await r.claimEvalRunDispatch(a)).toEqual({state:'dispatched',jobId:rotated});
 await r.deleteUndispatchedEvalRun(projectId,run.id);expect(await r.getEvalRun(projectId,run.id)).not.toBeNull();
 const untouched=await r.createEvalRun(input);await r.deleteUndispatchedEvalRun(projectId,untouched.id);expect(await r.getEvalRun(projectId,untouched.id)).toBeNull();
 const deliveries=await r.listPendingEvalRunItemDispatches(projectId,run.id);expect(await r.listPendingEvalRunItemDispatches(projectId,run.id)).toEqual(deliveries);
 expect(await r.listPendingEvalRunItems(projectId,run.id)).toHaveLength(1);
 const item=run.items[0]!;expect((await r.getEvalRunItem(projectId,run.id,item.id))?.caseId).toBe(trace.caseId);
 expect(await r.getEvalRunItem('other',run.id,item.id)).toBeNull();
 await r.armEvalRunItemDeliveryDeadline(projectId,run.id);
 const execution={projectId,evalRunId:run.id,evalRunItemId:item.id,executionToken:'recovery'};
 expect(await r.claimEvalRunItemRecovery(execution)).toBe(false);
 db.prepare('UPDATE eval_run_items SET delivery_deadline_at=0 WHERE id=?').run(item.id);
 expect(await r.listStaleEvalRunItemExecutions()).toMatchObject([{evalRunItemId:item.id}]);
 expect(await r.claimEvalRunItemRecovery(execution)).toBe(true);
 expect(await r.rearmEvalRunItemDeliveryDeadline(projectId,run.id,item.id)).toBe(false);
 expect(await r.releaseEvalRunItemExecution(execution,{preservePreCallClaim:true})).toEqual({state:'pre_call_held'});
 expect(await r.releaseEvalRunItemExecution(execution)).toEqual({state:'released'});
 expect(await r.rearmEvalRunItemDeliveryDeadline(projectId,run.id,item.id)).toBe(true);
 const released=await r.importTrace(projectId,'release_evidence',{input:'release',output:'evidence',metadata:{}},{ingestionPurpose:'release_evidence'});
 const empty=await r.createEvalRun({projectId,skillVersionId:version,trigger:'release_evidence',items:[{caseId:released.caseId,clientItemId:'released',contentDigest:'sha256:'+'a'.repeat(64)}]});
 const receiptExecution={projectId,evalRunId:empty.id,evalRunItemId:empty.items[0]!.id,executionToken:'receipt'};
 expect(await r.claimEvalRunItemExecution(receiptExecution)).toEqual({state:'claimed'});
 await r.failEvalRunItem({...receiptExecution,error:'Synthetic pre-dispatch refusal',failure:{state:'not_attempted'}});
 const receipt=(await r.getOrFreezeAssessmentReceipt(projectId,empty.id))!;
 expect(await r.getAssessmentReceiptArtifactByReceiptId(projectId,receipt.receiptId)).toEqual(receipt);
 expect(await r.getAssessmentReceiptArtifactByReceiptId('other',receipt.receiptId)).toBeNull();
});
